# Copyright Spectro Cloud 2026, 0
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.27.2
    hooks:
      - id: gitleaks
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
