/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * APIEndpoint represents a reachable Kubernetes API endpoint.
 */
export type APIEndpoint = {
  /** The hostname on which the API server is serving. */
  host: string;
  /** The port on which the API server is serving. */
  port: number;
};
