/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * APIServerAccessProfile - access profile for AKS API server.
 */
export type APIServerAccessProfile = {
  /** AuthorizedIPRanges - Authorized IP Ranges to kubernetes API server. */
  authorizedIPRanges?: string[];
  /** EnablePrivateCluster - Whether to create the cluster as a private cluster or not. */
  enablePrivateCluster?: boolean;
  /** EnablePrivateClusterPublicFQDN - Whether to create additional public FQDN for private cluster or not. */
  enablePrivateClusterPublicFQDN?: boolean;
  /** PrivateDNSZone - Private dns zone mode for private cluster. */
  privateDNSZone?: string;
};
