/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppDeploymentConfig } from './appDeploymentConfig';
import type { AppDeploymentProfile } from './appDeploymentProfile';

/**
 * Application deployment spec
 */
export type AppDeploymentSpec = {
  config?: AppDeploymentConfig;
  profile?: AppDeploymentProfile;
};
