/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppDeploymentClusterRefDeploymentClusterType } from './appDeploymentClusterRefDeploymentClusterType';

/**
 * Application deployment cluster reference
 */
export type AppDeploymentClusterRef = {
  /** Application deployment source cluster type[ "virtualCluster", "hostCluster" ] */
  deploymentClusterType?: AppDeploymentClusterRefDeploymentClusterType;
  /** Application deployment cluster name */
  name?: string;
  /** Application deployment cluster uid */
  uid?: string;
};
