/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Application deployment target environment reference
 */
export type AppDeploymentTargetEnvironmentRef = {
  /** Application deployment target resource name */
  name?: string;
  /** Application deployment target resource type [ "nestedCluster", "clusterGroup" ] */
  type?: string;
  /** Application deployment target resource uid */
  uid?: string;
};
