/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AppDeploymentClusterStatus } from './appDeploymentClusterStatus';
import type { AppDeploymentNotifications } from './appDeploymentNotifications';

/**
 * Application deployment status summary
 */
export type AppDeploymentStatusSummary = {
  cluster?: AppDeploymentClusterStatus;
  notifications?: AppDeploymentNotifications;
  state?: string;
};
