/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Application deployment source cluster type[ "virtualCluster", "hostCluster" ]
 */
export type AppDeploymentClusterRefDeploymentClusterType = typeof AppDeploymentClusterRefDeploymentClusterType[keyof typeof AppDeploymentClusterRefDeploymentClusterType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppDeploymentClusterRefDeploymentClusterType = {
  virtual: 'virtual',
  host: 'host',
} as const;
