/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppDeploymentConfigSummary } from './appDeploymentConfigSummary';
import type { AppDeploymentProfileSummary } from './appDeploymentProfileSummary';

/**
 * Application deployment spec summary
 */
export type AppDeploymentSummarySpec = {
  config?: AppDeploymentConfigSummary;
  profile?: AppDeploymentProfileSummary;
};
