/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type AppDeploymentSortFields = typeof AppDeploymentSortFields[keyof typeof AppDeploymentSortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppDeploymentSortFields = {
  appDeploymentName: 'appDeploymentName',
  creationTimestamp: 'creationTimestamp',
  lastModifiedTimestamp: 'lastModifiedTimestamp',
} as const;
