/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AppDeploymentClusterRef } from './appDeploymentClusterRef';
import type { AppDeploymentTargetEnvironmentRef } from './appDeploymentTargetEnvironmentRef';

/**
 * Application deployment target config response
 */
export type AppDeploymentTargetConfig = {
  clusterRef?: AppDeploymentClusterRef;
  envRef?: AppDeploymentTargetEnvironmentRef;
};
