/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AppDeploymentFilterSpec } from './appDeploymentFilterSpec';
import type { AppDeploymentSortSpec } from './appDeploymentSortSpec';

/**
 * Application deployment filter summary spec
 */
export type AppDeploymentsFilterSpec = {
  filter?: AppDeploymentFilterSpec;
  sort?: AppDeploymentSortSpec[];
};
