/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppDeploymentProfileVersion } from './appDeploymentProfileVersion';
import type { AppDeploymentProfileMeta } from './appDeploymentProfileMeta';

/**
 * Application deployment profile versions
 */
export type AppDeploymentProfileVersions = {
  /** Application deployment profile available versions */
  availableVersions?: AppDeploymentProfileVersion[];
  /** Application deployment profile latest versions */
  latestVersions?: AppDeploymentProfileVersion[];
  metadata?: AppDeploymentProfileMeta;
};
