/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppProfileMetaUpdateEntityAnnotations } from './appProfileMetaUpdateEntityAnnotations';
import type { AppProfileMetaUpdateEntityLabels } from './appProfileMetaUpdateEntityLabels';

/**
 * Application profile metadata update request payload
 */
export type AppProfileMetaUpdateEntity = {
  /** Application profile annotations */
  annotations?: AppProfileMetaUpdateEntityAnnotations;
  /** Application profile labels */
  labels?: AppProfileMetaUpdateEntityLabels;
};
