/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMetaInputEntity } from './objectMetaInputEntity';
import type { AppProfileEntitySpec } from './appProfileEntitySpec';

/**
 * Application profile request payload
 */
export type AppProfileEntity = {
  metadata?: ObjectMetaInputEntity;
  /** Application profile spec */
  spec?: AppProfileEntitySpec;
};
