/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { AppProfileSpec } from './appProfileSpec';
import type { AppProfileStatus } from './appProfileStatus';

/**
 * Application profile response
 */
export type AppProfile = {
  metadata?: ObjectMeta;
  spec?: AppProfileSpec;
  /** Application profile status */
  status?: AppProfileStatus;
};
