/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { FilterString } from './filterString';
import type { FilterArray } from './filterArray';
import type { FilterVersionString } from './filterVersionString';

/**
 * Application profile filter spec
 */
export type AppProfileFilterSpec = {
  profileName?: FilterString;
  tags?: FilterArray;
  version?: FilterVersionString;
};
