/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { AppProfileSummarySpec } from './appProfileSummarySpec';

/**
 * Application profile summary
 */
export type AppProfileSummary = {
  metadata?: ObjectMeta;
  /** Application profile spec summary */
  spec?: AppProfileSummarySpec;
};
