/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type AppProfileSortFields = typeof AppProfileSortFields[keyof typeof AppProfileSortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppProfileSortFields = {
  profileName: 'profileName',
  creationTimestamp: 'creationTimestamp',
  lastModifiedTimestamp: 'lastModifiedTimestamp',
} as const;
