/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppTierType } from './appTierType';

/**
 * Application tier reference
 */
export type AppTierRef = {
  /** Application tier name */
  name?: string;
  type?: AppTierType;
  /** Application tier uid to uniquely identify the tier */
  uid?: string;
  /** Application tier version */
  version?: string;
};
