/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AppTierResolvedValuesResolved } from './appTierResolvedValuesResolved';

/**
 * Application tier resolved macro values
 */
export type AppTierResolvedValues = {
  /** Application tier resolved macro values map */
  resolved?: AppTierResolvedValuesResolved;
};
