/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectReference } from './objectReference';
import type { AppTierProperty } from './appTierProperty';
import type { AppTierType } from './appTierType';

/**
 * Application tier specs
 */
export type AppTierSpec = {
  /** Application tier container registry uid */
  containerRegistryUid?: string;
  /** Application tier installation order */
  installOrder?: number;
  /** Application tier attached manifest content in yaml format */
  manifests?: ObjectReference[];
  /** Application tier properties */
  properties?: AppTierProperty[];
  /** Registry uid */
  registryUid?: string;
  /** Application tier source pack uid */
  sourceAppTierUid?: string;
  type?: AppTierType;
  /** Application tier configuration values in yaml format */
  values?: string;
  /** Application tier version */
  version?: string;
};
