/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Application tier property object
 */
export type AppTierPropertyEntity = {
  /** Application tier property name */
  name?: string;
  /** Application tier property value */
  value?: string;
};
