/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AppTierEntity } from './appTierEntity';

/**
 * Application tier patch request payload
 */
export type AppTierPatchEntity = {
  appTier?: AppTierEntity;
  /** Application tier UID to be replaced with new tier */
  replaceWithAppTier?: string;
};
