/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ManifestRefUpdateEntity } from './manifestRefUpdateEntity';
import type { AppTierPropertyEntity } from './appTierPropertyEntity';

/**
 * Application tier update request payload
 */
export type AppTierUpdateEntity = {
  /** Application tier container registry uid */
  containerRegistryUid?: string;
  /** Application tier installation order */
  installOrder?: number;
  /** Application tier manifests */
  manifests?: ManifestRefUpdateEntity[];
  /** Application tier name */
  name?: string;
  /** Application tier properties */
  properties?: AppTierPropertyEntity[];
  /** Application tier configuration values in yaml format */
  values?: string;
  /** Application tier version */
  version?: string;
};
