/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type AppTierType = typeof AppTierType[keyof typeof AppTierType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AppTierType = {
  manifest: 'manifest',
  helm: 'helm',
  'operator-instance': 'operator-instance',
  container: 'container',
} as const;
