/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ReleaseVersion } from './releaseVersion';

/**
 * spectro application management app version information
 */
export type AppVersion = {
  intermediateVersions?: ReleaseVersion[];
  latestVerson?: ReleaseVersion;
};
