/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { AsyncResult } from './asyncResult';

export type AsyncStatus = {
  endTime?: Time;
  result?: AsyncResult;
  stage?: string;
  startTime?: Time;
};
