/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AuditActorActorType } from './auditActorActorType';
import type { ProjectMeta } from './projectMeta';
import type { UserMeta } from './userMeta';

/**
 * Audit actor object
 */
export type AuditActor = {
  actorType?: AuditActorActorType;
  project?: ProjectMeta;
  serviceName?: string;
  user?: UserMeta;
};
