/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Audit resource reference object
 */
export type AuditResourceReference = {
  /** Audit resource type */
  kind?: string;
  /** Audit resource label */
  label?: string;
  /** Audit resource name */
  name?: string;
  /** Audit resource uid */
  uid: string;
};
