/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Audit user message update request payload
 */
export type AuditMsgUpdate = {
  /**
   * User message
   * @minLength 3
   * @maxLength 255
   */
  userMsg?: string;
};
