/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type AuditsListActionType = typeof AuditsListActionType[keyof typeof AuditsListActionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuditsListActionType = {
  create: 'create',
  update: 'update',
  delete: 'delete',
  publish: 'publish',
  deploy: 'deploy',
  activity: 'activity',
  action: 'action',
} as const;
