/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AuthLoginsAuthType } from './authLoginsAuthType';
import type { AuthLoginEntity } from './authLoginEntity';

/**
 * Deprecated. Applicable auth logins with multiple orgs
 */
export type AuthLogins = {
  appEnv?: string;
  /** Deprecated. */
  authType?: AuthLoginsAuthType;
  /** Deprecated. */
  orgName?: string;
  orgs?: AuthLoginEntity[];
  /** Deprecated. */
  redirectUrl?: string;
};
