/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

/**
 * Aws secret account credentials
 */
export type AwsAccountCredentials = {
  /** Aws account access key */
  accessKey?: string;
  expirationTime?: Time;
  /** Aws account secret key */
  secretKey?: string;
  /** Aws account secret token */
  secretToken?: string;
};
