/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsAmiReferenceEksOptimizedLookupType } from './awsAmiReferenceEksOptimizedLookupType';

/**
 * AMI is the reference to the AMI from which to create the machine instance
 */
export type AwsAmiReference = {
  /** EKSOptimizedLookupType If specified, will look up an EKS Optimized image in SSM Parameter store */
  eksOptimizedLookupType?: AwsAmiReferenceEksOptimizedLookupType;
  /** ID of resource */
  id?: string;
};
