/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { AwsCloudAccount } from './awsCloudAccount';
import type { CloudAccountStatus } from './cloudAccountStatus';

/**
 * Aws cloud account information
 */
export type AwsAccount = {
  apiVersion?: string;
  kind?: string;
  metadata?: ObjectMeta;
  spec?: AwsCloudAccount;
  status?: CloudAccountStatus;
};
