/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsCloudAccount } from './awsCloudAccount';
import type { AwsCloudCostSpecFilter } from './awsCloudCostSpecFilter';

/**
 * Aws cloud account usage cost payload spec
 */
export type AwsCloudCostSpec = {
  /** AccountId of AWS cloud cost */
  accountId?: string;
  credentials: AwsCloudAccount;
  filter?: AwsCloudCostSpecFilter;
};
