/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type AwsCloudCostSummaryMonthlyCost = {
  /** Amount for aws cloud cost */
  amount?: number;
  /** Time duration for aws cloud cost */
  timestamp?: number;
};
