/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

/**
 * Aws cloud account usage cost payload filter. startTime and endTime should be within 12 months range from now.
 */
export type AwsCloudCostSpecFilter = {
  endTime?: Time;
  /** IAM UserId of AWS account */
  iamUserId?: string;
  startTime: Time;
};
