/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Allowed Values [secret, sts]. STS type will be used for role assumption for sts type, accessKey/secretKey contains the source account, Arn is the target account.
 */
export type AwsCloudAccountCredentialType = typeof AwsCloudAccountCredentialType[keyof typeof AwsCloudAccountCredentialType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AwsCloudAccountCredentialType = {
  secret: 'secret',
  sts: 'sts',
} as const;
