/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectReference } from './objectReference';
import type { AwsClusterConfig } from './awsClusterConfig';
import type { AwsHybridMachinePool } from './awsHybridMachinePool';
import type { AwsMachinePoolConfig } from './awsMachinePoolConfig';

/**
 * AwsCloudConfigSpec defines the cloud configuration input by user This will translate to clusterspec/machinespec for cluster-api
 */
export type AwsCloudConfigSpec = {
  cloudAccountRef?: ObjectReference;
  clusterConfig?: AwsClusterConfig;
  hybridMachinePools?: AwsHybridMachinePool[];
  machinePoolConfig?: AwsMachinePoolConfig[];
};
