/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { IamRolesAnywhere } from './iamRolesAnywhere';
import type { SystemsManager } from './systemsManager';

/**
 * AwsHybridConfig specifies the AWS Hybrid configuration for the cluster
 */
export type AwsHybridConfig = {
  /** AWS VPC CIDR is the CIDR of the AWS/EKS cluster's VPC */
  awsVpcCidr?: string;
  iamRolesAnywhere?: IamRolesAnywhere;
  /** RemoteNodeCIDRs specifies the Node CIDRs of all remote nodes */
  remoteNodeCidrs?: string[];
  /** RemotePodCIDRs specifies the Pod CIDRs of all remote pods */
  remotePodCidrs?: string[];
  systemsManager?: SystemsManager;
};
