/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * AWS image name and ami
 */
export type AwsImage = {
  /** AWS image id */
  id?: string;
  /** AWS image name */
  name?: string;
  /** AWS image owner id */
  owner?: string;
};
