/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * AWS KMS Key - gives you centralized control over the cryptographic keys used to protect your data.
 */
export type AwsKmsKey = {
  /** AWS KMS alias */
  keyAlias?: string;
  /** AWS KMS arn */
  keyArn: string;
  /** AWS KMS keyid */
  keyId: string;
};
