/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * List of AWS keypairs
 */
export type AwsKeyPairs = {
  /** Array of Aws Keypair names */
  keyNames?: string[];
};
