/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AwsResourceReference } from './awsResourceReference';
import type { AwsAmiReference } from './awsAmiReference';
import type { AwsRootVolume } from './awsRootVolume';

/**
 * AWSLaunchTemplate specifies the launch template to use to create the managed node group
 */
export type AwsLaunchTemplate = {
  /** AdditionalSecurityGroups is an array of references to security groups that should be applied to the instances */
  additionalSecurityGroups?: AwsResourceReference[];
  ami?: AwsAmiReference;
  /** ImageLookupBaseOS is the name of the base operating system to use for image lookup the AMI is not set */
  imageLookupBaseOS?: string;
  /** ImageLookupFormat is the AMI naming format to look up the image */
  imageLookupFormat?: string;
  /** ImageLookupOrg is the AWS Organization ID to use for image lookup if AMI is not set */
  imageLookupOrg?: string;
  rootVolume?: AwsRootVolume;
};
