/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AwsMachinePoolConfigAdditionalLabels } from './awsMachinePoolConfigAdditionalLabels';
import type { AwsResourceReference } from './awsResourceReference';
import type { AwsMachinePoolConfigAdditionalTags } from './awsMachinePoolConfigAdditionalTags';
import type { AwsMachinePoolConfigCapacityType } from './awsMachinePoolConfigCapacityType';
import type { InstanceConfig } from './instanceConfig';
import type { MachinePoolProperties } from './machinePoolProperties';
import type { SpotMarketOptions } from './spotMarketOptions';
import type { AwsMachinePoolConfigSubnetIds } from './awsMachinePoolConfigSubnetIds';
import type { Taint } from './taint';
import type { UpdateStrategy } from './updateStrategy';

export type AwsMachinePoolConfig = {
  /** additionalLabels */
  additionalLabels?: AwsMachinePoolConfigAdditionalLabels;
  /** Additional Security groups */
  additionalSecurityGroups?: AwsResourceReference[];
  /** AdditionalTags is an optional set of tags to add to resources managed by the provider, in addition to the ones added by default. For eg., tags for EKS nodeGroup or EKS NodegroupIAMRole */
  additionalTags?: AwsMachinePoolConfigAdditionalTags;
  /** AZs is only used for dynamic placement */
  azs?: string[];
  /** EC2 instance capacity type */
  capacityType?: AwsMachinePoolConfigCapacityType;
  instanceConfig?: InstanceConfig;
  /** instance type */
  instanceType?: string;
  /** whether this pool is for control plane */
  isControlPlane: boolean;
  /** labels for this pool, example: control-plane/worker, gpu, windows */
  labels?: string[];
  machinePoolProperties?: MachinePoolProperties;
  /** max size of the pool, for scaling */
  maxSize?: number;
  /** min size of the pool, for scaling */
  minSize?: number;
  name?: string;
  /** Minimum number of seconds a node should be Ready, before the next node is selected for repave. Applicable only for workerpools in infrastructure cluster */
  nodeRepaveInterval?: number;
  /** rootDeviceSize in GBs */
  rootDeviceSize?: number;
  /** size of the pool, number of machines */
  size?: number;
  spotMarketOptions?: SpotMarketOptions;
  /** AZ to subnet mapping filled by ally from hubble SubnetIDs ["us-west-2d"] = "subnet-079b6061" This field is optional If we don't provide a subnetId then by default the first private subnet from the AZ will be picked up for deployment */
  subnetIds?: AwsMachinePoolConfigSubnetIds;
  /** control plane or worker taints */
  taints?: Taint[];
  updateStrategy?: UpdateStrategy;
  /** if IsControlPlane==true && useControlPlaneAsWorker==true, then will remove control plane taint this will not be used for worker pools */
  useControlPlaneAsWorker?: boolean;
};
