/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsResourceReference } from './awsResourceReference';
import type { AwsMachinePoolCloudConfigEntityCapacityType } from './awsMachinePoolCloudConfigEntityCapacityType';
import type { SpotMarketOptions } from './spotMarketOptions';
import type { AwsSubnetEntity } from './awsSubnetEntity';

export type AwsMachinePoolCloudConfigEntity = {
  /** Additional Security groups */
  additionalSecurityGroups?: AwsResourceReference[];
  azs?: string[];
  /** EC2 instance capacity type */
  capacityType?: AwsMachinePoolCloudConfigEntityCapacityType;
  /** instance type */
  instanceType: string;
  /**
   * rootDeviceSize in GBs
   * @minimum 1
   * @maximum 2000
   */
  rootDeviceSize?: number;
  spotMarketOptions?: SpotMarketOptions;
  subnets?: AwsSubnetEntity[];
};
