/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsResourceReference } from './awsResourceReference';
import type { AwsNic } from './awsNic';

/**
 * AWS cloud VM definition spec
 */
export type AwsMachineSpec = {
  /** Additional Security groups */
  additionalSecurityGroups?: AwsResourceReference[];
  ami: string;
  az?: string;
  dnsName?: string;
  iamProfile?: string;
  instanceType: string;
  nics?: AwsNic[];
  phase?: string;
  sshKeyName?: string;
  subnetId?: string;
  type?: string;
  vpcId: string;
};
