/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * AWS accounts are scoped to a single partition. Allowed values [aws, aws-us-gov], Default values
 */
export type AwsPartition = typeof AwsPartition[keyof typeof AwsPartition];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AwsPartition = {
  aws: 'aws',
  'aws-us-gov': 'aws-us-gov',
} as const;
