/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Volume encapsulates the configuration options for the storage device.
 */
export type AwsRootVolume = {
  /** Device name */
  deviceName?: string;
  /** EncryptionKey is the KMS key to use to encrypt the volume. Can be either a KMS key ID or ARN */
  encrypted?: boolean;
  /** EncryptionKey is the KMS key to use to encrypt the volume. Can be either a KMS key ID or ARN */
  encryptionKey?: string;
  /** IOPS is the number of IOPS requested for the disk. Not applicable to all types */
  iops?: number;
  /** Throughput to provision in MiB/s supported for the volume type. Not applicable to all types. */
  throughput?: number;
  /** Type is the type of the volume (e.g. gp2, io1, etc...) */
  type?: string;
};
