/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsResourceFilter } from './awsResourceFilter';

/**
 * AWSResourceReference is a reference to a specific AWS resource by ID or filters
 */
export type AwsResourceReference = {
  /** ARN of resource */
  arn?: string;
  /** Filters is a set of key/value pairs used to identify a resource */
  filters?: AwsResourceFilter[];
  /** ID of resource */
  id?: string;
};
