/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * AWS region which represents separate geographic area.
 */
export type AwsRegion = {
  /** AWS offer a regional endpoint that can used to make requests */
  endpoint?: string;
  /** Name of the AWS region */
  name?: string;
  /** Enable your account to operate in the particular regions */
  optInStatus?: string;
};
