/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * A subnet is a range of IP addresses in a AWS VPC
 */
export type AwsSubnet = {
  /** Every subnet can only be associated with only one Availability Zone */
  az?: string;
  /** Is this subnet private */
  isPrivate?: boolean;
  /** Indicates whether instances launched in this subnet receive a public IPv4 address. */
  mapPublicIpOnLaunch?: boolean;
  /** Name of the subnet */
  name?: string;
  /** Id of the subnet */
  subnetId?: string;
};
