/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Aws sts credentials
 */
export type AwsStsCredentials = {
  /** Arn for the aws sts credentials in cloud account */
  arn?: string;
  /** ExternalId for the aws sts credentials in cloud account */
  externalId?: string;
};
