/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AwsSecretTlsConfig } from './awsSecretTlsConfig';

/**
 * AWS cloud account which includes access key and secret key in case of 'secret' credentials type. It includes policyARNS, ARN and externalId in case of sts. Partition is a group of AWS Region and Service objects
 */
export type AwsSecretSpec = {
  /** AWS secret accountName; only for aws-iso-b environment */
  accountName?: string;
  /** AWS secret agency */
  agency?: string;
  /** Flag to rotate the secret region credentials */
  isCapValidationEnabled?: boolean;
  /** AWS secret mission; only for aws-iso environment */
  mission?: string;
  /** Policy Boundary */
  namePrefix?: string;
  /** Role or Policy Prefix */
  permissionBoundary?: string;
  /** AWS secret policy; JSON string */
  policy?: string;
  /** AWS secret role */
  role?: string;
  tls?: AwsSecretTlsConfig;
};
