/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsSecretSpecInputEntityPartition } from './awsSecretSpecInputEntityPartition';
import type { AwsSecretSpec } from './awsSecretSpec';

/**
 * AWS Secret spec input entity
 */
export type AwsSecretSpecInputEntity = {
  /** AWS accounts are scoped to a single partition. Allowed values [aws-iso, aws-iso-b], Default values */
  partition?: AwsSecretSpecInputEntityPartition;
  secretSpec?: AwsSecretSpec;
};
