/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * AWS accounts are scoped to a single partition. Allowed values [aws-iso, aws-iso-b], Default values
 */
export type AwsSecretSpecInputEntityPartition = typeof AwsSecretSpecInputEntityPartition[keyof typeof AwsSecretSpecInputEntityPartition];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AwsSecretSpecInputEntityPartition = {
  'aws-iso': 'aws-iso',
  'aws-iso-b': 'aws-iso-b',
} as const;
