/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsCloudAccount } from './awsCloudAccount';

/**
 * AWS S3 Bucket credentials
 */
export type AwsS3BucketCredentials = {
  /** Name of AWS S3 bucket */
  bucket: string;
  credentials: AwsCloudAccount;
  /** Name of the folder in the specified AWS S3 bucket. */
  folder?: string;
  /** Name of the available AWS region. */
  region: string;
};
