/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsCloudAccount } from './awsCloudAccount';

export type AwsUserCloudAccount = {
  accountId?: string;
  cloudAccount?: AwsCloudAccount;
};
