/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { AzureCloudAccount } from './azureCloudAccount';
import type { CloudAccountStatus } from './cloudAccountStatus';

/**
 * Azure account information
 */
export type AzureAccount = {
  /** Cloud account api version */
  apiVersion?: string;
  /** Cloud account kind */
  kind?: string;
  metadata?: ObjectMeta;
  spec?: AzureCloudAccount;
  status?: CloudAccountStatus;
};
