/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AzureAvailabilityZone } from './azureAvailabilityZone';

/**
 * Azure region entity
 */
export type AzureRegion = {
  /** Azure region displayname */
  displayName?: string;
  /** Azure region name */
  name?: string;
  /** List of zones associated to a particular Azure region */
  zones?: AzureAvailabilityZone[];
};
