/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { V1AzureAccountEntitySpec } from './v1AzureAccountEntitySpec';

/**
 * Azure storage config object
 */
export type AzureStorageConfig = {
  /** Azure container name */
  containerName: string;
  credentials: V1AzureAccountEntitySpec;
  /** Azure resource group name, to which the storage account is mapped */
  resourceGroup: string;
  /** Azure sku */
  sku?: string;
  /** Azure storage name */
  storageName: string;
};
