/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AzureMachineSpecAdditionalTags } from './azureMachineSpecAdditionalTags';
import type { AzureMachineSpecAvailabilityZone } from './azureMachineSpecAvailabilityZone';
import type { AzureMachineSpecImage } from './azureMachineSpecImage';
import type { AzureNic } from './azureNic';
import type { AzureOSDisk } from './azureOSDisk';

/**
 * Azure cloud VM definition spec
 */
export type AzureMachineSpec = {
  additionalTags?: AzureMachineSpecAdditionalTags;
  allocatePublicIP?: boolean;
  availabilityZone?: AzureMachineSpecAvailabilityZone;
  image?: AzureMachineSpecImage;
  instanceType: string;
  location: string;
  nics?: AzureNic[];
  osDisk: AzureOSDisk;
  sshPublicKey?: string;
};
