/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Contains configuration for Azure cloud
 */
export type AzureCloudAccountAzureEnvironment = typeof AzureCloudAccountAzureEnvironment[keyof typeof AzureCloudAccountAzureEnvironment];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AzureCloudAccountAzureEnvironment = {
  AzureChinaCloud: 'AzureChinaCloud',
  AzurePublicCloud: 'AzurePublicCloud',
  AzureUSGovernment: 'AzureUSGovernment',
  AzureUSGovernmentCloud: 'AzureUSGovernmentCloud',
  AzureUSSecretCloud: 'AzureUSSecretCloud',
} as const;
