/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { StorageContainer } from './storageContainer';

/**
 * List of Azure storage containers
 */
export type AzureStorageContainers = {
  containers?: StorageContainer[];
};
