/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * this map will be for ansible roles present in eack pack
 */
export type AzureCloudConfigStatusRoleDigest = {[key: string]: string};
