/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectReference } from './objectReference';
import type { AzureClusterConfig } from './azureClusterConfig';
import type { AzureMachinePoolConfig } from './azureMachinePoolConfig';

/**
 * AzureCloudConfigSpec defines the cloud configuration input by user This will translate to clusterspec/machinespec for cluster-api
 */
export type AzureCloudConfigSpec = {
  cloudAccountRef?: ObjectReference;
  clusterConfig?: AzureClusterConfig;
  machinePoolConfig?: AzureMachinePoolConfig[];
};
