/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Azure Private DNS zone entity
 */
export type AzurePrivateDnsZone = {
  /** Fully qualified resource Id for the resource */
  id?: string;
  /** The Azure Region where the resource lives */
  location?: string;
  /** The name of the resource */
  name?: string;
};
