/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AzureCloudAccountAzureEnvironment } from './azureCloudAccountAzureEnvironment';
import type { CloudAccountSettings } from './cloudAccountSettings';
import type { AzureSecretTlsConfig } from './azureSecretTlsConfig';

export type AzureCloudAccount = {
  /** Contains configuration for Azure cloud */
  azureEnvironment?: AzureCloudAccountAzureEnvironment;
  /** Client ID(Directory ID) is a unique identifier generated by Azure AD that is tied to an application */
  clientId: string;
  /** ClientSecret is the secret associated with Client */
  clientSecret: string;
  settings?: CloudAccountSettings;
  /** Tenant ID is the ID for the Azure AD tenant that the user belongs to. */
  tenantId: string;
  /** Tenant ID is the ID for the Azure AD tenant that the user belongs to. */
  tenantName?: string;
  tls?: AzureSecretTlsConfig;
};
