/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AzureAccount } from './azureAccount';
import type { ListMetaData } from './listMetaData';

export type AzureAccounts = {
  items: AzureAccount[];
  listmeta?: ListMetaData;
};
