/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AADProfile } from './aADProfile';
import type { APIServerAccessProfile } from './aPIServerAccessProfile';
import type { Subnet } from './subnet';
import type { InfraLBConfig } from './infraLBConfig';

/**
 * Cluster level configuration for Azure cloud and applicable for all the machine pools
 */
export type AzureClusterConfig = {
  aadProfile?: AADProfile;
  apiServerAccessProfile?: APIServerAccessProfile;
  containerName?: string;
  controlPlaneSubnet?: Subnet;
  /** Deprecated. use apiServerAccessProfile.enablePrivateCluster */
  enablePrivateCluster?: boolean;
  infraLBConfig?: InfraLBConfig;
  /** Location is the Azure datacenter location */
  location: string;
  resourceGroup?: string;
  sshKey: string;
  storageAccountName?: string;
  /** Subscription ID is unique identifier for the subscription used to access Azure services */
  subscriptionId: string;
  vnetCidrBlock?: string;
  /** VNETName is the virtual network in which the cluster is to be provisioned. */
  vnetName?: string;
  vnetResourceGroup?: string;
  workerSubnet?: Subnet;
};
