/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { RegistryAuth } from './registryAuth';
import type { BasicOciRegistrySpecProviderType } from './basicOciRegistrySpecProviderType';

/**
 * Basic oci registry spec
 */
export type BasicOciRegistrySpec = {
  auth: RegistryAuth;
  /** OCI registry content base path */
  baseContentPath?: string;
  /** OCI registry api base path */
  basePath?: string;
  containsSpectroManifest?: boolean;
  /** OCI registry endpoint */
  endpoint: string;
  isSyncSupported?: boolean;
  providerType?: BasicOciRegistrySpecProviderType;
  /** Basic oci registry uid */
  registryUid?: string;
  scope?: string;
};
