/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Response for broker login request
 */
export type BrokerToken = {
  /** clientType indicates the type of the client making the request */
  clientType?: string;
  /** maximum number of clients that can subscribe to the subject */
  maxAllowedClients?: number;
  /** message context data can be used as contextual information for the message exchange */
  msgCtxData?: unknown;
  /** subjects that client can publish */
  publisherSubjects?: string[];
  /** subjects that client has subscribed */
  subscriberSubjects?: string[];
};
