/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Card details object
 */
export type Card = {
  /** Card brand */
  brand?: string;
  /** Country name the card belongs */
  country?: string;
  /** Expiry year of the card */
  expYear?: number;
  /** Finger print */
  fingerPrint?: string;
  /** Funding */
  funding?: string;
  /** Last 4 digit of the card */
  last4?: string;
};
