/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { CloudStackVpc } from './cloudStackVpc';

/**
 * List of CloudStack SSH key pairs
 */
export type CloudStackVpcs = {
  items: CloudStackVpc[];
};
