/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * CloudStack compute offering
 */
export type CloudStackOffering = {
  /** Number of CPU cores */
  cpuNumber?: number;
  /** CPU speed in MHz */
  cpuSpeed?: number;
  /** Display text for the offering */
  displayText?: string;
  /** Hypervisor snapshot reserve space as percentage */
  hypervisorSnapshotReserve?: number;
  /** Offering ID */
  id?: string;
  /** Whether the offering allows customization of CPU and memory */
  isCustomized?: boolean;
  /** Whether the offering allows customization of IOPS */
  isCustomizedIops?: boolean;
  /** Whether the VM is volatile (data is lost on stop/restart) */
  isVolatile?: boolean;
  /** Whether CPU usage is limited */
  limitCpuUse?: boolean;
  /** Maximum IOPS for customized offerings */
  maxIops?: number;
  /** Memory size in MB */
  memory?: number;
  /** Minimum IOPS for customized offerings */
  minIops?: number;
  /** Offering name */
  name?: string;
  /** Whether the offering supports high availability */
  offerHA?: boolean;
  /** Storage type (local or shared) */
  storageType?: string;
};
