/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * VPC configuration for CloudStack networks
 */
export type CloudStackVPCSpec = {
  /** CIDR block for the VPC */
  cidr?: string;
  /** VPC id */
  id?: string;
  /** VPC name */
  name?: string;
  /** VPC offering name */
  offering?: string;
};
