/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * CloudStack cloud account credentials
 */
export type CloudStackCloudAccount = {
  /** API Key for CloudStack authentication */
  apiKey: string;
  /** API URL for CloudStack management server */
  apiUrl: string;
  /** Cloudstack domain */
  domain?: string;
  /** Skip SSL certificate verification (default: false) */
  insecure?: boolean;
  /** Secret Key for CloudStack authentication */
  secretKey: string;
};
