/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Cloud cost data point information
 */
export type CloudCostDataPoint = {
  compute?: number;
  storage?: number;
  timestamp?: number;
  total?: number;
};
