/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMetaUpdateEntity } from './objectMetaUpdateEntity';
import type { CloudStackCloudAccount } from './cloudStackCloudAccount';
import type { CloudAccountStatus } from './cloudAccountStatus';

/**
 * CloudStack account update entity
 */
export type CloudStackAccountUpdateEntity = {
  metadata?: ObjectMetaUpdateEntity;
  spec?: CloudStackCloudAccount;
  status?: CloudAccountStatus;
};
