/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { CloudStackCloudAccount } from './cloudStackCloudAccount';
import type { CloudAccountStatus } from './cloudAccountStatus';

/**
 * CloudStack account information
 */
export type CloudStackAccount = {
  /** Cloud account api version */
  apiVersion?: string;
  /** Cloud account kind */
  kind?: string;
  metadata?: ObjectMeta;
  spec?: CloudStackCloudAccount;
  status?: CloudAccountStatus;
};
