/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Cloud account settings
 */
export type CloudAccountSettings = {
  /** Will disable certain properties request to cloud and the input is collected directly from the user */
  disablePropertiesRequest?: boolean;
};
