/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { CloudResourceMetadataInstanceTypes } from './cloudResourceMetadataInstanceTypes';
import type { CloudResourceMetadataStorageTypes } from './cloudResourceMetadataStorageTypes';

/**
 * Cloud resource metadata
 */
export type CloudResourceMetadata = {
  instanceTypes?: CloudResourceMetadataInstanceTypes;
  storageTypes?: CloudResourceMetadataStorageTypes;
};
