/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Cloud category description
 */
export type CloudCategory = typeof CloudCategory[keyof typeof CloudCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CloudCategory = {
  datacenter: 'datacenter',
  cloud: 'cloud',
  edge: 'edge',
} as const;
