/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type CloudMachineStatusInstanceState = typeof CloudMachineStatusInstanceState[keyof typeof CloudMachineStatusInstanceState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CloudMachineStatusInstanceState = {
  Pending: 'Pending',
  Provisioning: 'Provisioning',
  Provisioned: 'Provisioned',
  Running: 'Running',
  Deleting: 'Deleting',
  Deleted: 'Deleted',
  Failed: 'Failed',
  Unknown: 'Unknown',
} as const;
