/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { CloudStackVPCSpec } from './cloudStackVPCSpec';

/**
 * Enhanced network configuration for CloudStack
 */
export type CloudStackNetworkSpec = {
  /** Gateway IP address for the network */
  gateway?: string;
  /** Network id */
  id?: string;
  /** Network name */
  name?: string;
  /** Network mask for the network */
  netmask?: string;
  /** Network offering name */
  offering?: string;
  /** Routing mode for the network */
  routingMode?: string;
  /** Network type: Isolated, Shared, etc. */
  type?: string;
  vpc?: CloudStackVPCSpec;
};
