/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ComputeRate } from './computeRate';
import type { StorageRate } from './storageRate';

/**
 * Cloud estimated rate information
 */
export type CloudRate = {
  compute?: ComputeRate;
  storage?: StorageRate[];
  total?: number;
};
