/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MachineHealth } from './machineHealth';
import type { CloudMachineStatusInstanceState } from './cloudMachineStatusInstanceState';
import type { MachineMaintenanceStatus } from './machineMaintenanceStatus';

/**
 * cloud machine status
 */
export type CloudMachineStatus = {
  health?: MachineHealth;
  instanceState?: CloudMachineStatusInstanceState;
  maintenanceStatus?: MachineMaintenanceStatus;
};
