/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { PackManifestsSpec } from './packManifestsSpec';
import type { PackSummaryStatus } from './packSummaryStatus';

/**
 * Cluster profile pack manifests
 */
export type ClusterProfilePackManifests = {
  metadata?: ObjectMeta;
  spec?: PackManifestsSpec;
  status?: PackSummaryStatus;
};
