/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { ClusterLogFetcherSpec } from './clusterLogFetcherSpec';
import type { ClusterLogFetcherStatus } from './clusterLogFetcherStatus';

/**
 * Cluster Log Fetcher
 */
export type ClusterLogFetcher = {
  metadata?: ObjectMeta;
  spec?: ClusterLogFetcherSpec;
  status?: ClusterLogFetcherStatus;
};
