/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterComplianceScanSyftDriverConfig } from './clusterComplianceScanSyftDriverConfig';

/**
 * Cluster compliance scan config for syft driver
 */
export type ClusterComplianceScanSyftConfig = {
  config?: ClusterComplianceScanSyftDriverConfig;
  runScan?: boolean;
};
