/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ResourceReference } from './resourceReference';
import type { ClusterResources } from './clusterResources';
import type { HostClusterConfig } from './hostClusterConfig';
import type { HybridClusterConfig } from './hybridClusterConfig';
import type { LifecycleConfig } from './lifecycleConfig';
import type { MachineHealthCheckConfig } from './machineHealthCheckConfig';
import type { MachineManagementConfig } from './machineManagementConfig';

export type ClusterConfig = {
  /** ClusterMetaAttribute contains additional cluster metadata information. */
  clusterMetaAttribute?: string;
  /** Deprecated. Use clusterResources */
  clusterRbac?: ResourceReference[];
  clusterResources?: ClusterResources;
  /** ControlPlaneHealthCheckTimeout is the timeout to check for ready state of the control plane nodes. If the node is not ready within the time out set, the node will be deleted and a new node will be launched. */
  controlPlaneHealthCheckTimeout?: string;
  hostClusterConfig?: HostClusterConfig;
  hybridClusterConfig?: HybridClusterConfig;
  lifecycleConfig?: LifecycleConfig;
  machineHealthConfig?: MachineHealthCheckConfig;
  machineManagementConfig?: MachineManagementConfig;
  /** Timezone of a cluster in IANA standard format. It is mandatory field if cluster is deployed through template, else it is optional */
  timezone?: string;
  /** UpdateWorkerPoolsInParallel is used to decide if the update of workerpools happen in parallel. When this flag is false, the workerpools are updated sequentially. */
  updateWorkerPoolsInParallel?: boolean;
};
