/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { ClusterComplianceScanSpec } from './clusterComplianceScanSpec';

/**
 * Cluster Compliance Scan
 */
export type ClusterComplianceScan = {
  metadata?: ObjectMeta;
  spec?: ClusterComplianceScanSpec;
};
