/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PackManifestEntity } from './packManifestEntity';
import type { ProfileType } from './profileType';

/**
 * Cluster profile template spec
 */
export type ClusterProfileTemplateDraft = {
  cloudType?: string;
  /** Cluster profile packs array */
  packs?: PackManifestEntity[];
  type?: ProfileType;
};
