/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type ClusterProfilesCreateParams = {
/**
 * If true then cluster profile will be created and published in a single transaction
 */
publish?: boolean;
};
