/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type ClusterComplianceScanSyftDriverConfigFormat = typeof ClusterComplianceScanSyftDriverConfigFormat[keyof typeof ClusterComplianceScanSyftDriverConfigFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterComplianceScanSyftDriverConfigFormat = {
  'cyclonedx-json': 'cyclonedx-json',
  'github-json': 'github-json',
  'spdx-json': 'spdx-json',
  'syft-json': 'syft-json',
} as const;
