/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterProfileFips } from './clusterProfileFips';
import type { ObjectEntity } from './objectEntity';
import type { ClusterProfilePackSummary } from './clusterProfilePackSummary';

/**
 * ClusterProfileStatusSummary defines the observed state of ClusterProfile
 */
export type ClusterProfileStatusSummary = {
  fips?: ClusterProfileFips;
  inUseClusterTemplates?: ObjectEntity[];
  /** Deprecated. Use inUseClusters */
  inUseClusterUids?: string[];
  inUseClusters?: ObjectEntity[];
  isPublished?: boolean;
  pack?: ClusterProfilePackSummary;
};
