/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterWorkloadPodContainer } from './clusterWorkloadPodContainer';
import type { ClusterWorkloadPodVolume } from './clusterWorkloadPodVolume';

/**
 * Cluster workload pod spec
 */
export type ClusterWorkloadPodSpec = {
  containers?: ClusterWorkloadPodContainer[];
  volumes?: ClusterWorkloadPodVolume[];
};
