/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Clusters grouped by reconciliation status
 */
export type ClusterReconcileStatusCountsClusters = {
  /** List of UIDs for clusters in applied state */
  applied?: string[];
  /** List of UIDs for clusters in failed state */
  failed?: string[];
  /** List of UIDs for clusters in pending state */
  pending?: string[];
};
