/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

export type ClusterCondition = {
  lastProbeTime?: Time;
  lastTransitionTime?: Time;
  /** Human-readable message indicating details about last transition. */
  message?: string;
  /** Unique, one-word, CamelCase reason for the condition's last transition. */
  reason?: string;
  status: string;
  type: string;
};
