/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SpectroClusterVariable } from './spectroClusterVariable';

/**
 * Cluster template profile information
 */
export type ClusterTemplateProfileVariable = {
  /** UID of the cluster profile */
  uid?: string;
  /** List of cluster profile variable values for the cluster to be updated. */
  variables?: SpectroClusterVariable[];
};
