/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type ClusterImport = {
  /** import link to download and install ally-lite, palette-lite */
  importLink?: string;
  /** Deprecated. Use the 'spec.clusterType' */
  isBrownfield?: boolean;
  /** cluster import status */
  state?: string;
};
