/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterFeatureActor } from './clusterFeatureActor';
import type { ClusterSonobuoyLogStatusReports } from './clusterSonobuoyLogStatusReports';
import type { ClusterScanTime } from './clusterScanTime';

/**
 * Cluster compliance scan Sonobuoy Log Status
 */
export type ClusterSonobuoyLogStatus = {
  actor?: ClusterFeatureActor;
  message?: string;
  reports?: ClusterSonobuoyLogStatusReports;
  requestUid?: string;
  scanTime?: ClusterScanTime;
  state?: string;
};
