/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Cluster along with specific variable value
 */
export type ClusterVariableValue = {
  /** UID of the cluster */
  uid?: string;
  /** Value of the variable */
  value?: string;
};
