/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { ClusterWorkloadRef } from './clusterWorkloadRef';
import type { ClusterWorkloadMetadataLabels } from './clusterWorkloadMetadataLabels';

/**
 * Cluster workload metadata
 */
export type ClusterWorkloadMetadata = {
  creationTimestamp?: Time;
  entity?: ClusterWorkloadRef;
  labels?: ClusterWorkloadMetadataLabels;
  namespace?: string;
};
