/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterCondition } from './clusterCondition';
import type { Time } from './time';
import type { ClusterPackManifestStatus } from './clusterPackManifestStatus';
import type { LoadBalancerService } from './loadBalancerService';

export type ClusterPackStatus = {
  condition?: ClusterCondition;
  endTime?: Time;
  manifests?: ClusterPackManifestStatus[];
  name?: string;
  profileUid?: string;
  services?: LoadBalancerService[];
  startTime?: Time;
  type?: string;
  version?: string;
};
