/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { PackManifestUpdateEntity } from './packManifestUpdateEntity';

/**
 * Cluster profile notification update request payload
 */
export type ClusterProfileNotificationUpdateEntity = {
  /** Cluster profile packs array */
  packs?: PackManifestUpdateEntity[];
  /** Cluster profile uid */
  uid?: string;
};
