/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterProfileNotificationUpdateEntity } from './clusterProfileNotificationUpdateEntity';
import type { SpcApplySettings } from './spcApplySettings';

/**
 * Cluster input for notification update
 */
export type ClusterNotificationUpdateEntity = {
  profiles?: ClusterProfileNotificationUpdateEntity[];
  spcApplySettings?: SpcApplySettings;
};
