/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterFipsMode } from './clusterFipsMode';
import type { FilterString } from './filterString';
import type { ProfileType } from './profileType';
import type { ClusterProfileScope } from './clusterProfileScope';
import type { FilterArray } from './filterArray';
import type { FilterVersionString } from './filterVersionString';

/**
 * Cluster profile filter spec
 */
export type ClusterProfileFilterSpec = {
  environment?: string[];
  fips?: ClusterFipsMode;
  profileName?: FilterString;
  profileType?: ProfileType[];
  scope?: ClusterProfileScope;
  tags?: FilterArray;
  version?: FilterVersionString;
};
