/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterFeatureActor } from './clusterFeatureActor';
import type { ClusterKubeHunterLogStatusReports } from './clusterKubeHunterLogStatusReports';
import type { ClusterScanTime } from './clusterScanTime';

/**
 * Cluster compliance scan KubeHunter Log Status
 */
export type ClusterKubeHunterLogStatus = {
  actor?: ClusterFeatureActor;
  message?: string;
  reports?: ClusterKubeHunterLogStatusReports;
  requestUid?: string;
  scanTime?: ClusterScanTime;
  state?: string;
};
