/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * State of the variable assignment
 */
export type ClusterTemplateVariableClusterAssignmentAssignmentState = typeof ClusterTemplateVariableClusterAssignmentAssignmentState[keyof typeof ClusterTemplateVariableClusterAssignmentAssignmentState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterTemplateVariableClusterAssignmentAssignmentState = {
  Pending: 'Pending',
  Assigned: 'Assigned',
} as const;
