/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterRbacBinding } from './clusterRbacBinding';
import type { RelatedObject } from './relatedObject';

/**
 * Cluster RBAC spec
 */
export type ClusterRbacSpec = {
  bindings?: ClusterRbacBinding[];
  /** Set to true when the binding is created automatically by the system, rather than manually by the user */
  isSystem?: boolean;
  relatedObject?: RelatedObject;
};
