/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { RelatedObject } from './relatedObject';
import type { ClusterNamespaceResourceAllocation } from './clusterNamespaceResourceAllocation';

/**
 * Cluster namespace spec
 */
export type ClusterNamespaceSpec = {
  isRegex?: boolean;
  relatedObject?: RelatedObject;
  resourceAllocation?: ClusterNamespaceResourceAllocation;
};
