/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Current reconciliation state
 */
export type ClusterReconcileStatusState = typeof ClusterReconcileStatusState[keyof typeof ClusterReconcileStatusState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterReconcileStatusState = {
  Created: 'Created',
  Pending: 'Pending',
  InProgress: 'InProgress',
  Applied: 'Applied',
  Failed: 'Failed',
} as const;
