/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { PolicyRef } from './policyRef';
import type { ClusterTemplateProfile } from './clusterTemplateProfile';

/**
 * Cluster template specification
 */
export type ClusterTemplateEntitySpec = {
  /** Type of cloud provider */
  cloudType?: string;
  /** List of policy references */
  policies?: PolicyRef[];
  /** List of cluster profile references */
  profiles?: ClusterTemplateProfile[];
};
