/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterTemplateProfileVariableWithClusters } from './clusterTemplateProfileVariableWithClusters';

/**
 * Response for retrieving variables for a specific profile in a cluster template
 */
export type ClusterTemplateProfileVariablesResponse = {
  /** List of variables with cluster assignments */
  variables?: ClusterTemplateProfileVariableWithClusters[];
};
