/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterReconcileStatusCounts } from './clusterReconcileStatusCounts';
import type { ClusterVariableStatus } from './clusterVariableStatus';
import type { ClusterTemplateMaintenanceStatus } from './clusterTemplateMaintenanceStatus';
import type { ClusterTemplateStatusState } from './clusterTemplateStatusState';

/**
 * Cluster template status
 */
export type ClusterTemplateStatus = {
  clusterStatusCounts?: ClusterReconcileStatusCounts;
  clusterVariables?: ClusterVariableStatus;
  maintenance?: ClusterTemplateMaintenanceStatus;
  /** Current state of the cluster template */
  state?: ClusterTemplateStatusState;
};
