/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { PolicyRef } from './policyRef';

/**
 * Cluster template policies update entity
 */
export type ClusterTemplatePoliciesUpdateEntity = {
  /** List of spc policy references to be updated in the cluster template */
  policies: PolicyRef[];
};
