/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterWorkloadMetadata } from './clusterWorkloadMetadata';
import type { ClusterWorkloadDeploymentStatus } from './clusterWorkloadDeploymentStatus';

/**
 * Cluster workload deployment summary
 */
export type ClusterWorkloadDeployment = {
  metadata?: ClusterWorkloadMetadata;
  status?: ClusterWorkloadDeploymentStatus;
};
