/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterHelmRegistry } from './clusterHelmRegistry';

/**
 * Cluster helm chart metadata
 */
export type ClusterHelmChart = {
  localName?: string;
  matchedRegistries?: ClusterHelmRegistry[];
  name?: string;
  values?: string;
  version?: string;
};
