/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterComplianceScanKubeBenchConfig } from './clusterComplianceScanKubeBenchConfig';
import type { ClusterComplianceScanKubeHunterConfig } from './clusterComplianceScanKubeHunterConfig';
import type { ClusterComplianceScanSonobuoyConfig } from './clusterComplianceScanSonobuoyConfig';
import type { ClusterComplianceScanSyftConfig } from './clusterComplianceScanSyftConfig';

/**
 * Cluster compliance scan on demand configuration
 */
export type ClusterComplianceOnDemandConfig = {
  kubeBench?: ClusterComplianceScanKubeBenchConfig;
  kubeHunter?: ClusterComplianceScanKubeHunterConfig;
  sonobuoy?: ClusterComplianceScanSonobuoyConfig;
  syft?: ClusterComplianceScanSyftConfig;
};
