/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterGroupClustersConfigEndpointType } from './clusterGroupClustersConfigEndpointType';
import type { ClusterGroupHostClusterConfig } from './clusterGroupHostClusterConfig';
import type { ClusterKubernetesDistroType } from './clusterKubernetesDistroType';
import type { ClusterGroupLimitConfig } from './clusterGroupLimitConfig';

/**
 * Clusters config of cluster group
 */
export type ClusterGroupClustersConfig = {
  /** Host cluster endpoint type */
  endpointType?: ClusterGroupClustersConfigEndpointType;
  hostClustersConfig?: ClusterGroupHostClusterConfig[];
  kubernetesDistroType?: ClusterKubernetesDistroType;
  limitConfig?: ClusterGroupLimitConfig;
  values?: string;
};
