/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterTemplateVariableClusterMapping } from './clusterTemplateVariableClusterMapping';

/**
 * Profile with variables and cluster assignments
 */
export type ClusterTemplateProfileVariablesGroup = {
  /** UID of the cluster profile */
  uid: string;
  /** List of variables with cluster assignments */
  variables: ClusterTemplateVariableClusterMapping[];
};
