/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterTemplateProfileVariablesVariables } from './clusterTemplateProfileVariablesVariables';

/**
 * Profile variables with grouped resolved and unresolved variables
 */
export type ClusterTemplateProfileVariables = {
  /** Profile name */
  name?: string;
  /** Profile UID */
  uid: string;
  /** List of resolved and unresolved variables belonging to a cluster launched from template */
  variables?: ClusterTemplateProfileVariablesVariables;
};
