/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type ClusterPairMetadataSortFields = typeof ClusterPairMetadataSortFields[keyof typeof ClusterPairMetadataSortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterPairMetadataSortFields = {
  name: 'name',
  state: 'state',
  creationTimestamp: 'creationTimestamp',
} as const;
