/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterTemplateMetadata } from './clusterTemplateMetadata';

export type ClusterTemplatesMetadata = {
  items: ClusterTemplateMetadata[];
};
