/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterRoleRef } from './clusterRoleRef';
import type { ClusterRbacSubjects } from './clusterRbacSubjects';
import type { ClusterRbacBindingType } from './clusterRbacBindingType';

/**
 * Cluster RBAC binding
 */
export type ClusterRbacBinding = {
  namespace?: string;
  role?: ClusterRoleRef;
  subjects?: ClusterRbacSubjects[];
  type?: ClusterRbacBindingType;
};
