/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { ClusterGroupSpec } from './clusterGroupSpec';
import type { ClusterGroupStatus } from './clusterGroupStatus';

/**
 * Cluster group information
 */
export type ClusterGroup = {
  metadata?: ObjectMeta;
  spec?: ClusterGroupSpec;
  status?: ClusterGroupStatus;
};
