/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterTemplateProfile } from './clusterTemplateProfile';

/**
 * Cluster template profiles update entity
 */
export type ClusterTemplateProfilesUpdateEntity = {
  /** List of cluster profile references with updated variable values and assign strategies */
  profiles: ClusterTemplateProfile[];
};
