/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Current state of the cluster template
 */
export type ClusterTemplateStatusState = typeof ClusterTemplateStatusState[keyof typeof ClusterTemplateStatusState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterTemplateStatusState = {
  Pending: 'Pending',
  Applied: 'Applied',
  Failed: 'Failed',
  PartiallyApplied: 'PartiallyApplied',
} as const;
