/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectReference } from './objectReference';
import type { PackRef } from './packRef';

/**
 * ClusterProfileTemplate contains details of a clusterprofile definition
 */
export type ClusterProfileTemplate = {
  cloudType?: string;
  name?: string;
  /** PackServerRefs is only used on Hubble side it is reference to pack registry servers which PackRef belongs to in hubble, pack server is a top level object, so use a reference to point to it packs within a clusterprofile can come from different pack servers, so this is an array */
  packServerRefs?: ObjectReference[];
  /** This secret is used only on Palette side use case is similar  to k8s image pull secret this single secret internally should contains all the pack servers in PackServerRefs if empty, means no credential is needed to access the pack server For spectro saas, Ally will set this field before pass to palette */
  packServerSecret?: string;
  /** Packs definitions here are final definitions. If ClonedFrom and ParamsOverwrite is present, then Packs are the final merge result of ClonedFrom and ParamsOverwrite So orchestration engine will just take the Packs and do the work, no need to worry about parameters merge */
  packs?: PackRef[];
  /** version start from 1.0.0, matching the index of ClusterProfileSpec.Versions[] will be used by clusterSpec to identify which version is applied to the cluster */
  profileVersion?: string;
  relatedObject?: ObjectReference;
  type?: string;
  uid?: string;
  /** Deprecated. Use profileVersion */
  version?: number;
};
