/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type ClusterHybridSettingsEntity = {
  /** Property which is used to enable a cluster to perform hybrid operations */
  enable?: boolean;
};
