/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterWorkloadMetadata } from './clusterWorkloadMetadata';
import type { ClusterWorkloadCronJobSpec } from './clusterWorkloadCronJobSpec';
import type { ClusterWorkloadCronJobStatus } from './clusterWorkloadCronJobStatus';

/**
 * Cluster workload cronjob summary
 */
export type ClusterWorkloadCronJob = {
  metadata?: ClusterWorkloadMetadata;
  spec?: ClusterWorkloadCronJobSpec;
  status?: ClusterWorkloadCronJobStatus;
};
