/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectEntity } from './objectEntity';

/**
 * Provides status information for cluster templates like in use cluster which are launched using the template
 */
export type ClusterTemplateSummaryStatus = {
  inUseClusters?: ObjectEntity[];
  /** The reconciliation state of the cluster template */
  state?: string;
};
