/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterWorkloadRoleBinding } from './clusterWorkloadRoleBinding';

/**
 * Cluster workload rbac bindings summary
 */
export type ClusterWorkloadRoleBindings = {
  bindings?: ClusterWorkloadRoleBinding[];
};
