/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterWorkloadMetadata } from './clusterWorkloadMetadata';
import type { ClusterWorkloadStatefulSetStatus } from './clusterWorkloadStatefulSetStatus';

/**
 * Cluster workload statefulset summary
 */
export type ClusterWorkloadStatefulSet = {
  metadata?: ClusterWorkloadMetadata;
  status?: ClusterWorkloadStatefulSetStatus;
};
