/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterGroupClusterRef } from './clusterGroupClusterRef';
import type { ClusterGroupClustersConfig } from './clusterGroupClustersConfig';
import type { SpectroClusterProfileEntity } from './spectroClusterProfileEntity';
import type { ClusterGroupSpecEntityType } from './clusterGroupSpecEntityType';

/**
 * Cluster group specifications request entity
 */
export type ClusterGroupSpecEntity = {
  clusterRefs?: ClusterGroupClusterRef[];
  clustersConfig?: ClusterGroupClustersConfig;
  profiles?: SpectroClusterProfileEntity[];
  type?: ClusterGroupSpecEntityType;
};
