/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Filter cluster profiles by target resource type - 'spectrocluster' for profiles suitable to launch clusters, 'clustertemplate' for profiles suitable to create/edit cluster template
 */
export type ClusterProfileResourceType = typeof ClusterProfileResourceType[keyof typeof ClusterProfileResourceType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterProfileResourceType = {
  spectrocluster: 'spectrocluster',
  clustertemplate: 'clustertemplate',
} as const;
