/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMetaUpdateEntity } from './objectMetaUpdateEntity';
import type { ClusterNamespaceSpec } from './clusterNamespaceSpec';

/**
 * Cluster Namespace resource definition
 */
export type ClusterNamespaceResourceInputEntity = {
  metadata?: ObjectMetaUpdateEntity;
  spec?: ClusterNamespaceSpec;
};
