/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type ClusterRepaveSource = typeof ClusterRepaveSource[keyof typeof ClusterRepaveSource];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterRepaveSource = {
  user: 'user',
  hubble: 'hubble',
  palette: 'palette',
  stylus: 'stylus',
} as const;
