/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterProfileMetadataImportEntity } from './clusterProfileMetadataImportEntity';
import type { ClusterProfileSpecImportEntity } from './clusterProfileSpecImportEntity';

/**
 * Cluster profile import request payload
 */
export type ClusterProfileImportEntity = {
  metadata?: ClusterProfileMetadataImportEntity;
  spec?: ClusterProfileSpecImportEntity;
};
