/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { ClusterRestoreSpec } from './clusterRestoreSpec';
import type { ClusterRestoreStatus } from './clusterRestoreStatus';

/**
 * Cluster Restore
 */
export type ClusterRestore = {
  metadata?: ObjectMeta;
  spec?: ClusterRestoreSpec;
  status?: ClusterRestoreStatus;
};
