/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type ClusterTemplatesSortFields = typeof ClusterTemplatesSortFields[keyof typeof ClusterTemplatesSortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClusterTemplatesSortFields = {
  clusterTemplateName: 'clusterTemplateName',
  cloudType: 'cloudType',
  creationTimestamp: 'creationTimestamp',
  lastModifiedTimestamp: 'lastModifiedTimestamp',
} as const;
