/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { PackSummarySpec } from './packSummarySpec';
import type { PackSummaryStatus } from './packSummaryStatus';

/**
 * Cluster profile packs object
 */
export type ClusterProfilePacksEntity = {
  metadata?: ObjectMeta;
  spec?: PackSummarySpec;
  status?: PackSummaryStatus;
};
