/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmDataVolumeTemplateSpec } from './vmDataVolumeTemplateSpec';
import type { VmInstancetypeMatcher } from './vmInstancetypeMatcher';
import type { VmPreferenceMatcher } from './vmPreferenceMatcher';
import type { VmVirtualMachineInstanceTemplateSpec } from './vmVirtualMachineInstanceTemplateSpec';

/**
 * VirtualMachineSpec describes how the proper VirtualMachine should look like
 */
export type ClusterVirtualMachineSpec = {
  /** dataVolumeTemplates is a list of dataVolumes that the VirtualMachineInstance template can reference. DataVolumes in this list are dynamically created for the VirtualMachine and are tied to the VirtualMachine's life-cycle. */
  dataVolumeTemplates?: VmDataVolumeTemplateSpec[];
  instancetype?: VmInstancetypeMatcher;
  preference?: VmPreferenceMatcher;
  /** Running state indicates the requested running state of the VirtualMachineInstance mutually exclusive with Running */
  runStrategy?: string;
  /** Running controls whether the associatied VirtualMachineInstance is created or not Mutually exclusive with RunStrategy */
  running?: boolean;
  template: VmVirtualMachineInstanceTemplateSpec;
};
