/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * cluster preference
 */
export type ClusterPreference = {
  /** clusters cleanup interval post deletion */
  archivalIntervalInHour?: number;
  /** clusters deleted before delete period are eligible for cleanup */
  deletePeriodInHour?: number;
  /**
   * clusters health poll interval
   * @minimum 3
   * @maximum 60
   */
  healthPollIntervalInMinutes?: number;
  /** clusters state and consistency monitor */
  monitorIntervalInMinutes?: number;
};
