/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Describes the system's reverse proxy server protocol. Possible values [https, http]
 */
export type ConfigReverseProxyProtocol = typeof ConfigReverseProxyProtocol[keyof typeof ConfigReverseProxyProtocol];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConfigReverseProxyProtocol = {
  http: 'http',
  https: 'https',
} as const;
