/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type ControlPlaneHealthCheckTimeoutEntity = {
  /** ControlPlaneHealthCheckTimeout is the timeout to check for ready state of the control plane nodes */
  controlPlaneHealthCheckTimeout?: string;
};
