/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * VIP or External
 */
export type ControlPlaneEndPointType = typeof ControlPlaneEndPointType[keyof typeof ControlPlaneEndPointType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ControlPlaneEndPointType = {
  VIP: 'VIP',
  External: 'External',
  DDNS: 'DDNS',
} as const;
