/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ControlPlaneEndPointType } from './controlPlaneEndPointType';

export type ControlPlaneEndPoint = {
  /** DDNSSearchDomain is the search domain used for resolving IP addresses when the EndpointType is DDNS. This search domain is appended to the generated Hostname to obtain the complete DNS name for the endpoint. If Host is already a DDNS FQDN, DDNSSearchDomain is not required */
  ddnsSearchDomain?: string;
  /** IP or FQDN(External/DDNS) */
  host?: string;
  /** VIP or External */
  type?: ControlPlaneEndPointType;
};
