/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { CustomMachinePoolConfigAdditionalLabels } from './customMachinePoolConfigAdditionalLabels';
import type { Taint } from './taint';

export type CustomMachinePoolConfig = {
  /** additionalLabels */
  additionalLabels?: CustomMachinePoolConfigAdditionalLabels;
  /** whether this pool is for control plane */
  isControlPlane: boolean;
  name?: string;
  /** size of the pool, number of machines */
  size?: number;
  /** control plane or worker taints */
  taints?: Taint[];
  /** if IsControlPlane==true && useControlPlaneAsWorker==true, then will remove control plane taint this will not be used for worker pools */
  useControlPlaneAsWorker?: boolean;
  /** YAML string for machine */
  values?: string;
};
