/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Additional labels to be part of the machine pool
 */
export type CustomMachinePoolBaseConfigEntityAdditionalLabels = { [key: string]: unknown };
