/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterLocation } from './clusterLocation';
import type { MachineManagementConfig } from './machineManagementConfig';
import type { ClusterResourcesEntity } from './clusterResourcesEntity';

export type CustomClusterConfigEntity = {
  location?: ClusterLocation;
  machineManagementConfig?: MachineManagementConfig;
  resources?: ClusterResourcesEntity;
  /** The timezone field is mandatory if cluster is deployed through template, else it is optional */
  timezone?: string;
};
