/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { DashboardWorkspaceMeta } from './dashboardWorkspaceMeta';
import type { ObjectMeta } from './objectMeta';
import type { DashboardWorkspaceSpec } from './dashboardWorkspaceSpec';
import type { DashboardWorkspaceStatus } from './dashboardWorkspaceStatus';

/**
 * Workspace information
 */
export type DashboardWorkspace = {
  meta?: DashboardWorkspaceMeta;
  metadata?: ObjectMeta;
  spec?: DashboardWorkspaceSpec;
  status?: DashboardWorkspaceStatus;
};
