/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type DashboardSpectroClustersRepaveListRepaveState = typeof DashboardSpectroClustersRepaveListRepaveState[keyof typeof DashboardSpectroClustersRepaveListRepaveState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DashboardSpectroClustersRepaveListRepaveState = {
  Pending: 'Pending',
  Approved: 'Approved',
  Reverted: 'Reverted',
} as const;
