/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GpuConfig } from './gpuConfig';

/**
 * Workspace quota resource allocation
 */
export type DashboardWorkspaceQuotaResourceAllocation = {
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  cpu?: number;
  gpuConfig?: GpuConfig;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  memory?: number;
};
