/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Credits allocated for each tenant/user
 */
export type DeveloperCredit = {
  /** cpu in cores */
  cpu?: number;
  /** memory in GiB */
  memoryGiB?: number;
  /** storage in GiB */
  storageGiB?: number;
  /** number of active virtual clusters */
  virtualClustersLimit?: number;
};
