/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Architecture type of the edge host
 */
export type DeviceSpecArchType = typeof DeviceSpecArchType[keyof typeof DeviceSpecArchType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeviceSpecArchType = {
  arm64: 'arm64',
  amd64: 'amd64',
} as const;
