/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EcrAuthorizationRequestEntity } from './ecrAuthorizationRequestEntity';
import type { EcrImageEntity } from './ecrImageEntity';

/**
 * Ecr registry image meta
 */
export type EcrImageValidateEntity = {
  authEntity?: EcrAuthorizationRequestEntity;
  /** Name of the image tag */
  imageTag?: string;
  /** Ecr Image Entity */
  images?: EcrImageEntity[];
  /** Name of the repo */
  repoName?: string;
};
