/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { EcrRegistrySpec } from './ecrRegistrySpec';
import type { OciRegistryStatus } from './ociRegistryStatus';

/**
 * Ecr registry information
 */
export type EcrRegistry = {
  kind?: string;
  metadata?: ObjectMeta;
  spec?: EcrRegistrySpec;
  status?: OciRegistryStatus;
};
