/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { EdgeHostNetworkNetworkType } from './edgeHostNetworkNetworkType';

/**
 * Network defines the network configuration for a virtual machine
 */
export type EdgeHostNetwork = {
  /** NetworkName of the network where this machine will be connected */
  networkName: string;
  /** NetworkType  specifies the type of network */
  networkType: EdgeHostNetworkNetworkType;
};
