/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { EdgeNativeHybridClusterConfig } from './edgeNativeHybridClusterConfig';
import type { EdgeNativeHybridMachineConfigEntity } from './edgeNativeHybridMachineConfigEntity';
import type { SpectroClusterProfileEntity } from './spectroClusterProfileEntity';

/**
 * EdgeNativeHybridMachineConfigEntity defines Edge Native machine configuration
 */
export type EdgeNativeHybridConfigEntity = {
  clusterConfig?: EdgeNativeHybridClusterConfig;
  machineCloudConfig?: EdgeNativeHybridMachineConfigEntity;
  /** Cluster profile templates for edge-native machine pool */
  profiles?: SpectroClusterProfileEntity[];
};
