/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * RemoteSsh controls the remote SSH access for this edge host
 */
export type EdgeHostRemoteSsh = typeof EdgeHostRemoteSsh[keyof typeof EdgeHostRemoteSsh];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EdgeHostRemoteSsh = {
  enabled: 'enabled',
  disabled: 'disabled',
} as const;
