/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { EdgeNativeCloudConfigSpec } from './edgeNativeCloudConfigSpec';
import type { EdgeNativeCloudConfigStatus } from './edgeNativeCloudConfigStatus';

/**
 * EdgeNativeCloudConfig is the Schema for the edgenativecloudconfigs API
 */
export type EdgeNativeCloudConfig = {
  metadata?: ObjectMeta;
  spec?: EdgeNativeCloudConfigSpec;
  status?: EdgeNativeCloudConfigStatus;
};
