/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ArchType } from './archType';
import type { EdgeNativeHybridMachinePoolHost } from './edgeNativeHybridMachinePoolHost';

/**
 * EdgeNativeHybridMachineConfigEntity defines Edge Native machine configuration
 */
export type EdgeNativeHybridMachineConfigEntity = {
  archType: ArchType;
  /** Edge hosts configurations */
  edgeHosts: EdgeNativeHybridMachinePoolHost[];
};
