/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Deprecated. Cloudtype of the provisioned edge host
 */
export type EdgeHostDeviceSpecType = typeof EdgeHostDeviceSpecType[keyof typeof EdgeHostDeviceSpecType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EdgeHostDeviceSpecType = {
  vsphere: 'vsphere',
  'edge-native': 'edge-native',
} as const;
