/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type EdgeHostDeviceStatusState = typeof EdgeHostDeviceStatusState[keyof typeof EdgeHostDeviceStatusState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EdgeHostDeviceStatusState = {
  ready: 'ready',
  unpaired: 'unpaired',
  'in-use': 'in-use',
} as const;
