/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { EdgeHostSSHSecret } from './edgeHostSSHSecret';

export type EdgeHostIdentity = {
  /** CACert is the client CA certificate */
  caCert?: string;
  /** Mode indicates a system or session connection to the host */
  mode?: string;
  /** SocketPath is an optional path to the socket on the host, if not using defaults */
  socketPath?: string;
  sshSecret?: EdgeHostSSHSecret;
};
