/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Sets the Edge Host candidate priority as either primary or secondary. This field is applicable only when the Edge Host is nominated as a two-node candidate. To enable priority assignment, ensure that 'isTwoNodeCluster' is set to true.

 */
export type EdgeNativeHostTwoNodeCandidatePriority = typeof EdgeNativeHostTwoNodeCandidatePriority[keyof typeof EdgeNativeHostTwoNodeCandidatePriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EdgeNativeHostTwoNodeCandidatePriority = {
  primary: 'primary',
  secondary: 'secondary',
} as const;
