/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type EdgeHostMetaEdgeHostType = typeof EdgeHostMetaEdgeHostType[keyof typeof EdgeHostMetaEdgeHostType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EdgeHostMetaEdgeHostType = {
  'edge-native': 'edge-native',
  vsphere: 'vsphere',
} as const;
