/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { EdgeHostCloudProperties } from './edgeHostCloudProperties';
import type { ClusterProfileTemplate } from './clusterProfileTemplate';
import type { DeviceSpec } from './deviceSpec';
import type { EdgeHost } from './edgeHost';
import type { EdgeHostProperties } from './edgeHostProperties';
import type { ServiceSpec } from './serviceSpec';
import type { SpectroTunnelConfig } from './spectroTunnelConfig';
import type { EdgeHostDeviceSpecType } from './edgeHostDeviceSpecType';

/**
 * EdgeHostDeviceSpec defines the desired state of EdgeHostDevice
 */
export type EdgeHostDeviceSpec = {
  cloudProperties?: EdgeHostCloudProperties;
  clusterProfileTemplates?: ClusterProfileTemplate[];
  device?: DeviceSpec;
  host?: EdgeHost;
  properties?: EdgeHostProperties;
  service?: ServiceSpec;
  tunnelConfig?: SpectroTunnelConfig;
  /** Deprecated. Cloudtype of the provisioned edge host */
  type?: EdgeHostDeviceSpecType;
  version?: string;
};
