/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EdgeHostHealth } from './edgeHostHealth';
import type { ObjectEntity } from './objectEntity';
import type { EdgeClusterObjectEntity } from './edgeClusterObjectEntity';
import type { ClusterPackStatus } from './clusterPackStatus';
import type { ProfileStatus } from './profileStatus';
import type { EdgeHostDeviceStatusState } from './edgeHostDeviceStatusState';
import type { SpectroTunnelStatus } from './spectroTunnelStatus';

/**
 * EdgeHostDeviceStatus defines the observed state of EdgeHostDevice
 */
export type EdgeHostDeviceStatus = {
  health?: EdgeHostHealth;
  /** Deprecated. Use inUseClustersRef */
  inUseClusters?: ObjectEntity[];
  inUseClustersRef?: EdgeClusterObjectEntity[];
  packs?: ClusterPackStatus[];
  profileStatus?: ProfileStatus;
  serviceAuthToken?: string;
  state?: EdgeHostDeviceStatusState;
  tunnelStatus?: SpectroTunnelStatus;
};
