/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type EdgeNativeOverlayNetworkConfiguration = {
  /** CIDR is the CIDR of the overlay network */
  cidr?: string;
  /** Enable is a flag to enable overlay network */
  enable?: boolean;
};
