/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { HybridClusterMeta } from './hybridClusterMeta';

/**
 * Object identity meta of the cluster
 */
export type EdgeClusterObjectEntity = {
  hybridCluster?: HybridClusterMeta;
  /** Name of the cluster */
  name?: string;
  /** Uid of the cluster */
  uid?: string;
};
