/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * System service login input
 */
export type EdgeServiceLogin = {
  /** authToken helps in two step verification for the authorization. */
  authToken?: string;
  edgeHostUid?: string;
  serviceName?: string;
  serviceVersion?: string;
  spectroClusterUid?: string;
  tenantUid?: string;
};
