/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { LifecycleConfig } from './lifecycleConfig';
import type { MachineManagementConfig } from './machineManagementConfig';
import type { ClusterResourcesEntity } from './clusterResourcesEntity';

export type EdgeNativeClusterConfigPairEntity = {
  controlPlaneHealthCheckTimeout?: string;
  lifecycleConfig?: LifecycleConfig;
  machineManagementConfig?: MachineManagementConfig;
  resources?: ClusterResourcesEntity;
  updateWorkerPoolsInParallel?: boolean;
};
