/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * EndpointAccess specifies how control plane endpoints are accessible
 */
export type EksClusterConfigEndpointAccess = {
  /** Private points VPC-internal control plane access to the private endpoint */
  private?: boolean;
  /** PrivateCIDRs specifies which blocks can access the private endpoint */
  privateCIDRs?: string[];
  /** Public controls whether control plane endpoints are publicly accessible */
  public?: boolean;
  /** PublicCIDRs specifies which blocks can access the public endpoint */
  publicCIDRs?: string[];
};
