/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * EC2 instance capacity type
 */
export type EksMachinePoolConfigCapacityType = typeof EksMachinePoolConfigCapacityType[keyof typeof EksMachinePoolConfigCapacityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EksMachinePoolConfigCapacityType = {
  'on-demand': 'on-demand',
  spot: 'spot',
} as const;
