/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * EC2 instance capacity type
 */
export type EksMachineCloudConfigEntityCapacityType = typeof EksMachineCloudConfigEntityCapacityType[keyof typeof EksMachineCloudConfigEntityCapacityType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EksMachineCloudConfigEntityCapacityType = {
  'on-demand': 'on-demand',
  spot: 'spot',
  'host-resource-group': 'host-resource-group',
} as const;
