/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * EncryptionConfig specifies the encryption configuration for the EKS clsuter.
 */
export type EncryptionConfig = {
  /** Is encryption configuration enabled for the cluster */
  isEnabled?: boolean;
  /** Provider specifies the ARN or alias of the CMK (in AWS KMS) */
  provider?: string;
  /** Resources specifies the resources to be encrypted */
  resources?: string[];
};
