/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type EventsMigrateTargetVersion = typeof EventsMigrateTargetVersion[keyof typeof EventsMigrateTargetVersion];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const EventsMigrateTargetVersion = {
  v1: 'v1',
  v2: 'v2',
} as const;
