/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EventsMigrateSourceVersion } from './eventsMigrateSourceVersion';
import type { EventsMigrateTargetVersion } from './eventsMigrateTargetVersion';

/**
 * Event migration request
 */
export type EventsMigrate = {
  sourceVersion?: EventsMigrateSourceVersion;
  targetVersion?: EventsMigrateTargetVersion;
};
