/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { FargateSelectorLabels } from './fargateSelectorLabels';

/**
 * FargateSelector specifies a selector for pods that should run on this fargate pool
 */
export type FargateSelector = {
  /** Labels specifies which pod labels this selector should match. */
  labels?: FargateSelectorLabels;
  /** Namespace specifies which namespace this selector should match. */
  namespace: string;
};
