/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { FargateProfileAdditionalTags } from './fargateProfileAdditionalTags';
import type { FargateSelector } from './fargateSelector';

/**
 * FargateProfile defines the desired state of FargateProfile
 */
export type FargateProfile = {
  /** AdditionalTags is an optional set of tags to add to AWS resources managed by the AWS provider, in addition to the ones added by default. */
  additionalTags?: FargateProfileAdditionalTags;
  /** name specifies the profile name. */
  name: string;
  /** Selectors specify fargate pod selectors. */
  selectors?: FargateSelector[];
  /** SubnetIDs specifies which subnets are used for the auto scaling group of this nodegroup. */
  subnetIds?: string[];
};
