/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type FilterVersionString = {
  /** @nullable */
  beginsWith?: string | null;
  /** @nullable */
  eq?: string | null;
  /** @nullable */
  gt?: string | null;
  /** @nullable */
  lt?: string | null;
  /** @nullable */
  ne?: string | null;
};
