/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type FilterString = {
  /** @nullable */
  beginsWith?: string | null;
  /** @nullable */
  contains?: string | null;
  /** @nullable */
  eq?: string | null;
  ignoreCase?: boolean;
  /** @nullable */
  ne?: string | null;
};
