/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { GcpAccountEntitySpec } from './gcpAccountEntitySpec';
import type { CloudAccountStatus } from './cloudAccountStatus';

/**
 * GCP account information
 */
export type GcpAccountEntity = {
  /** Cloud account api version */
  apiVersion?: string;
  /** Cloud account kind */
  kind?: string;
  metadata?: ObjectMeta;
  spec?: GcpAccountEntitySpec;
  status?: CloudAccountStatus;
};
