/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GcpManagedClusterConfig } from './gcpManagedClusterConfig';

/**
 * Cluster level configuration for gcp cloud and applicable for all the machine pools
 */
export type GcpClusterConfig = {
  managedClusterConfig?: GcpManagedClusterConfig;
  /** NetworkName if empty would create VPC Network in auto mode. If provided, custom VPC network will be used */
  network?: string;
  /** Name of the project in which cluster is to be deployed */
  project: string;
  /** GCP region for the cluster */
  region: string;
};
