/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterCondition } from './clusterCondition';
import type { GcpImage } from './gcpImage';
import type { GcpCloudConfigStatusRoleDigest } from './gcpCloudConfigStatusRoleDigest';

/**
 * GcpCloudConfigStatus defines the observed state of GcpCloudConfig The cloudimage info built by Mold is stored here image should be mapped to a specific machinepool
 */
export type GcpCloudConfigStatus = {
  /** For mold controller to identify if is there any changes in Pack */
  ansibleRoleDigest?: string;
  /** spectroAnsibleProvisioner: should be added only once, subsequent recocile will use the same provisioner SpectroAnsiblePacker bool `json:"spectroAnsiblePacker,omitempty"` */
  conditions?: ClusterCondition[];
  images?: GcpImage;
  /** addon layers present in spc */
  isAddonLayer?: boolean;
  /** this map will be for ansible roles present in each pack */
  roleDigest?: GcpCloudConfigStatusRoleDigest;
  /** sourceImageId, it can be from packref's annotations or from pack.json */
  sourceImageId?: string;
  /** PackerVariableDigest string `json:"packerDigest,omitempty"` If no ansible roles found in Packs then Mold should tell Drive to use capi image and not create custom image, because there is nothing to add */
  useCapiImage?: boolean;
};
