/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { InstanceConfig } from './instanceConfig';
import type { GcpNic } from './gcpNic';

/**
 * GCP cloud VM definition spec
 */
export type GcpMachineSpec = {
  image?: string;
  instanceConfig?: InstanceConfig;
  instanceType: string;
  nics?: GcpNic[];
  project?: string;
  region?: string;
  rootDeviceSize?: number;
  zone?: string;
};
