/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GcpSubnetEntity } from './gcpSubnetEntity';

export type GcpMachinePoolCloudConfigEntity = {
  azs?: string[];
  instanceType: string;
  /** Size of root volume in GB. Default is 30GB */
  rootDeviceSize?: number;
  /** Subnet specifies the subnetwork to use for given instance. If not specified, the first subnet from the cluster region and network is used */
  subnet?: string;
  subnets?: GcpSubnetEntity[];
};
