/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * GCP managed cluster config
 */
export type GcpManagedClusterConfig = {
  /** EnableAutopilot indicates whether to enable autopilot for this GKE cluster */
  enableAutoPilot?: boolean;
  /** Can be Region or Zone */
  location?: string;
};
