/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GcpSubnet } from './gcpSubnet';

/**
 * GCP network enity is a virtual version of a physical network
 */
export type GcpNetwork = {
  /** GCP network name */
  name?: string;
  /** List of GCP subnet */
  subnets?: GcpSubnet[];
};
