/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GcpProject } from './gcpProject';

/**
 * List of GCP Projects
 */
export type GcpProjects = {
  /** List of GCP Projects */
  projects?: GcpProject[];
};
