/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Geographical region made up of zones where you can host your GCP resources
 */
export type GcpRegion = {
  /** GCP region name */
  name?: string;
  /** GCP region status */
  status?: string;
};
