/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { GpuConfigProvider } from './gpuConfigProvider';

/**
 * GPU configuration for resource allocation
 */
export type GpuConfig = {
  /**
   * GPU resource limit
   * @minimum 0
   */
  limit?: number;
  /** GPU provider (only nvidia is supported currently) */
  provider?: GpuConfigProvider;
};
