/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { GPUDeviceSpecAddresses } from './gPUDeviceSpecAddresses';

export type GPUDeviceSpec = {
  /** Addresses is a map of PCI device entry name to its addresses.
Example entry would be "11:00.0 VGA compatible controller [0300]: NVIDIA
Corporation Device [10de:1eb1] (rev a1)"- > 0000_11_00_0" The address is
BDF (Bus Device Function) identifier format seperated by underscores. The
first 4 bits are almost always 0000. In the above example 11 is Bus, 00
is Device,0 is function. The values of these addreses are expected in hexadecimal
format
 */
  addresses?: GPUDeviceSpecAddresses;
  /** Number of GPUs */
  gpuCount?: number;
  /** GPU memory specification */
  memory?: string;
  /** MIG capability flag */
  migCapable?: boolean;
  /** MIG strategy configuration */
  migStrategy?: string;
  /** Model is the model of GPU, for a given vendor, for eg., TU104GL [Tesla T4] */
  model?: string;
  /** Vendor is the GPU vendor, for eg., NVIDIA or AMD */
  vendor?: string;
};
