/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GrpcServerMonitoringDataClients } from './grpcServerMonitoringDataClients';
import type { GrpcServerMonitoringDataSubjects } from './grpcServerMonitoringDataSubjects';

export type GrpcServerMonitoringData = {
  clients?: GrpcServerMonitoringDataClients;
  isError?: boolean;
  messageLogs?: string[];
  subjects?: GrpcServerMonitoringDataSubjects;
  totalClients?: number;
  totalSubjects?: number;
};
