/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { GrpcEndpointTls } from './grpcEndpointTls';

export type GrpcEndpoint = {
  /** Describes the URL where the client has to connect to the grpc server */
  endpoint?: string;
  /** Describes the Grpc tls config which client will use to make a request to the grpc server */
  tls?: GrpcEndpointTls;
};
