/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { HelmChartOption } from './helmChartOption';

/**
 * Helm registry create options
 */
export type HelmRegistryCreateOption = {
  charts?: HelmChartOption[];
  skipSync?: boolean;
};
