/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * is enabled as host cluster
 */
export type HostClusterEndpointType = typeof HostClusterEndpointType[keyof typeof HostClusterEndpointType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HostClusterEndpointType = {
  Ingress: 'Ingress',
  LoadBalancer: 'LoadBalancer',
} as const;
