/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { HostClusterEndpoint } from './hostClusterEndpoint';
import type { ObjectReference } from './objectReference';

export type HostClusterConfig = {
  clusterEndpoint?: HostClusterEndpoint;
  clusterGroup?: ObjectReference;
  hostCluster?: ObjectReference;
  /** is enabled as host cluster */
  isHostCluster?: boolean;
};
