/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ArchType } from './archType';
import type { EdgeNativeHybridMachinePoolHost } from './edgeNativeHybridMachinePoolHost';
import type { HybridCluster } from './hybridCluster';

/**
 * HybridEdgeNativeMachineCloudConfig defines hybrid Edge-Native cluster's machine configurations
 */
export type HybridEdgeNativeMachineCloudConfig = {
  archType: ArchType;
  /** Edge host's configuration */
  edgeHosts: EdgeNativeHybridMachinePoolHost[];
  hybridCluster?: HybridCluster;
};
