/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EdgeNativeHybridConfigEntity } from './edgeNativeHybridConfigEntity';
import type { MachinePoolConfigEntity } from './machinePoolConfigEntity';

/**
 * Hybrid Edge-Native cluster's machine-pool configuration request payload
 */
export type HybridEdgeNativeMachinePoolConfigEntity = {
  cloudConfig?: EdgeNativeHybridConfigEntity;
  poolConfig?: MachinePoolConfigEntity;
};
