/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { HybridPoolClusterRef } from './hybridPoolClusterRef';

export type HybridClusterConfig = {
  /** Parent cluster uid. Provided for hybrid (child) clusters only. */
  clusterUid?: string;
  /** Flag differentiating if the cluster is an hybrid cluster or not. True for a cluster with hybrid mode enabled, false for the actual hybrid (child) clusters */
  enable?: boolean;
  /** References to hybrid (child) clusters deployed within the hybrid cluster */
  hybridMachinePoolClusterRefs?: HybridPoolClusterRef[];
};
