/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EdgeNativeHybridMachineConfigEntity } from './edgeNativeHybridMachineConfigEntity';
import type { EdgeNativeHybridClusterConfig } from './edgeNativeHybridClusterConfig';
import type { MachinePoolConfigEntity } from './machinePoolConfigEntity';

/**
 * Hybrid Edge-Native cluster's machine-pool configuration update request payload
 */
export type HybridEdgeNativeMachinePoolConfigUpdateEntity = {
  cloudConfig?: EdgeNativeHybridMachineConfigEntity;
  clusterConfig?: EdgeNativeHybridClusterConfig;
  poolConfig?: MachinePoolConfigEntity;
};
