/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Object identity meta of hybrid cluster
 */
export type HybridClusterMeta = {
  /** Name of the hybrid cluster */
  name?: string;
  /** Uid of the hybrid cluster */
  uid?: string;
};
