/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { HybridMachinePoolStatus } from './hybridMachinePoolStatus';

/**
 * Metadata information related to a hybrid machine pool launched as part of an hybrid cluster
 */
export type HybridMachinePool = {
  /** Cloud config uid associated with the hybrid machine pool */
  cloudConfigUid?: string;
  /** Cloud type of the hybrid machine pool */
  cloudType?: string;
  /** Uid of the hybrid machine pool cluster */
  clusterUid?: string;
  /** Name of the hybrid machine pool */
  name?: string;
  status?: HybridMachinePoolStatus;
  /** Uid of the hybrid machine pool */
  uid?: string;
};
