/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { HybridEdgeNativeMachineCloudConfig } from './hybridEdgeNativeMachineCloudConfig';
import type { MachinePoolConfigEntity } from './machinePoolConfigEntity';

/**
 * HybridEdgeNativeMachinePoolConfig defines hybrid Edge-Native cluster's machine-pool configurations
 */
export type HybridEdgeNativeMachinePoolConfig = {
  cloudConfig?: HybridEdgeNativeMachineCloudConfig;
  poolConfig?: MachinePoolConfigEntity;
};
