/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * If the importMode is empty then cluster is imported with full permission mode. By default importMode is empty and cluster is imported in full permission mode.
 */
export type ImportClusterConfigImportMode = typeof ImportClusterConfigImportMode[keyof typeof ImportClusterConfigImportMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImportClusterConfigImportMode = {
  'read-only': 'read-only',
} as const;
