/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Specifies the scope of cluster-wide resources to include in the backup based on the flag'--include-cluster-resources':
- "Always": --include-cluster-resources=true, which includes all cluster-wide resources; restores only on the original cluster.
- "Auto": don't specify --include-cluster-resources, which exclude general cluster-wide resources, but includes PersistentVolumes linked to selected namespaces.
- "Never": --include-cluster-resources=false, exclude all cluster-wide resources, including PersistentVolumes.

 */
export type IncludeClusterResourceMode = typeof IncludeClusterResourceMode[keyof typeof IncludeClusterResourceMode];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const IncludeClusterResourceMode = {
  Always: 'Always',
  Auto: 'Auto',
  Never: 'Never',
} as const;
