/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type InstanceConfig = {
  category?: string;
  cpuSet?: number;
  diskGiB?: number;
  /** MemoryMiB is the size of a virtual machine's memory, in MiB */
  memoryMiB?: number;
  name?: string;
  /** NumCPUs is the number of virtual processors in a virtual machine */
  numCPUs?: number;
};
