/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Address } from './address';
import type { InvoiceBillingPeriod } from './invoiceBillingPeriod';
import type { InvoiceCredits } from './invoiceCredits';
import type { Time } from './time';
import type { InvoiceSpecPaymentUnit } from './invoiceSpecPaymentUnit';
import type { InvoicePlan } from './invoicePlan';

/**
 * Invoice specification
 */
export type InvoiceSpec = {
  address?: Address;
  billingPeriod?: InvoiceBillingPeriod;
  credits?: InvoiceCredits;
  /** Environment type [Trial,MonthlyOnDemand,AnnualSubscription,OnPrem] */
  envType?: string;
  month?: Time;
  paymentUnit?: InvoiceSpecPaymentUnit;
  plan?: InvoicePlan;
};
