/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ProjectUsage } from './projectUsage';

/**
 * Invoice project object
 */
export type InvoiceProject = {
  /** Billing amount for the project */
  amount?: number;
  /** Name of the project */
  projectName?: string;
  /** Project identifier */
  projectUid?: string;
  usage?: ProjectUsage;
};
