/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PlanCredit } from './planCredit';

/**
 * Invoice plan credit object
 */
export type InvoicePlanCredit = {
  planCredit?: PlanCredit;
  /** Total used cpu core hours */
  totalCpuCoreHours?: number;
};
