/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Nameserver } from './nameserver';
import type { Pool } from './pool';

/**
 * IPPool defines static IPs available. Gateway, Prefix, Nameserver, if defined, will be default values for all Pools
 */
export type IPPool = {
  /** Gateway is the gateway ip address */
  gateway?: string;
  nameserver?: Nameserver;
  /** Pools contains the list of IP addresses pools */
  pools?: Pool[];
  /** Prefix is the mask of the network as integer (max 128) */
  prefix?: number;
  /** UID is the UID of this IPPool, used by Hubble */
  uid?: string;
};
