/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * jet service login input
 */
export type JetServiceLogin = {
  /** authToken helps in two step verification for the authorization. */
  authKey?: string;
  edgeHostUid?: string;
  hostClusterUid?: string;
  isSystem?: boolean;
  jetUid?: string;
  overlordUid?: string;
  serviceVersion?: string;
  spectroClusterUid?: string;
  tenantUid?: string;
};
