/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { V1k8CertificateAuthority } from './v1k8CertificateAuthority';

/**
 * K8 Certificates for control plane nodes
 */
export type K8MachineCertificate = {
  /** Applicable certificate authorities */
  certificateAuthorities?: V1k8CertificateAuthority[];
  name?: string;
};
