/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Compliance Scan KubeHunter Vulnerabilities
 */
export type KubeHunterVulnerabilities = {
  high?: number;
  low?: number;
  medium?: number;
};
