/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { KubeHunterLogEntity } from './kubeHunterLogEntity';
import type { Time } from './time';
import type { KubeHunterVulnerabilityDataEntity } from './kubeHunterVulnerabilityDataEntity';

/**
 * KubeHunter report
 */
export type KubeHunterReportEntity = {
  logs?: KubeHunterLogEntity[];
  time?: Time;
  vulnerabilities?: KubeHunterVulnerabilityDataEntity;
};
