/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * ListMeta describes metadata for the resource listing
 */
export type ListMetaData = {
  /** Next token for the pagination. Next token is equal to empty string indicates end of result set. */
  continue?: string;
  /** Total count of the resources which might change during pagination based on the resources addition or deletion */
  count?: number;
  /** Number of records feteched */
  limit?: number;
  /** The next offset for the pagination. Starting index for which next request will be placed. */
  offset?: number;
};
