/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ServicePort } from './servicePort';

export type LoadBalancerService = {
  /** IP or Host from svc.Status.LoadBalancerStatus.Ingress */
  host?: string;
  /** name of the loadbalancer service */
  name?: string;
  /** port this service exposed */
  ports?: ServicePort[];
};
