/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { LoginResponseAuthType } from './loginResponseAuthType';
import type { SsoLogins } from './ssoLogins';

/**
 * Returns the allowed login method and information with the organization details
 */
export type LoginResponse = {
  /** Describes the env type. Possible values [ saas, self-hosted, quick-start, enterprise, airgap] */
  appEnv?: string;
  /** Describes the default mode of authentication. Possible values [password, sso] */
  authType?: LoginResponseAuthType;
  /** Organization name. */
  orgName?: string;
  /** Describes the default redirect Url for authentication. If authType is sso, it will have tenant configured saml/oidc idp url else it will be users organization url */
  redirectUrl?: string;
  /** Describes the domain url on which the saas is available */
  rootDomain?: string;
  /** Describes which security mode is enabled */
  securityMode?: string;
  ssoLogins?: SsoLogins;
  /** Describes the total number of tenant present in the system */
  totalTenants?: number;
};
