/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterCondition } from './clusterCondition';
import type { MaasImage } from './maasImage';
import type { MaasCloudConfigStatusRoleDigest } from './maasCloudConfigStatusRoleDigest';

/**
 * MaasCloudConfigStatus defines the observed state of MaasCloudConfig The cloudimage info built by Mold is stored here image should be mapped to a specific machinepool
 */
export type MaasCloudConfigStatus = {
  /** For mold controller to identify if is there any changes in Pack */
  ansibleRoleDigest?: string;
  conditions?: ClusterCondition[];
  /** addon layers present in spc */
  isAddonLayer?: boolean;
  nodeImage?: MaasImage;
  /** this map will be for ansible roles present in eack pack */
  roleDigest?: MaasCloudConfigStatusRoleDigest;
  /** sourceImageId, it can be from packref's annotations or from pack.json */
  sourceImageId?: string;
  /** PackerVariableDigest string `json:"packerDigest,omitempty"` If no ansible roles found in Packs then Mold should tell Drive to use capi image and not create custom image, because there is nothing to add */
  useCapiImage?: boolean;
};
