/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Cluster level configuration for MAAS cloud and applicable for all the machine pools
 */
export type MaasClusterConfig = {
  /** Domain name of the cluster to be provisioned */
  domain: string;
  /** enableLxdVm controls MaaS KVM host enablement for the Host ControlPlane cluster only.
When true, Palette configures MaasMachineTemplate LXD settings so LXD initialization
is triggered on nodes of this (host) cluster. This does not affect workload clusters.
Cannot be enabled for clusters where useLxdVm is enabled for any of the control plane machine pool configs. */
  enableLxdVm?: boolean;
  /** NTPServers is a list of NTP servers to use instead of the machine image's default NTP server list. */
  ntpServers?: string[];
  /** SSH keys specifies a list of ssh authorized keys for the 'spectro' user */
  sshKeys?: string[];
  /** whether this cluster should use dhcp or static IP, if false, use DHCP if this is set, then all machinepools should have staticIP with provided IPPool adding this as an additional standalone flag without relating to placement.Nework main reason is to enable more validation for placement.Network.StaticIP which should come together with valid Network.IPPool and Network.Name */
  staticIp?: boolean;
};
