/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { MaasMachineSpec } from './maasMachineSpec';
import type { CloudMachineStatus } from './cloudMachineStatus';

/**
 * Maas cloud VM definition
 */
export type MaasMachine = {
  apiVersion?: string;
  kind?: string;
  metadata?: ObjectMeta;
  spec?: MaasMachineSpec;
  status?: CloudMachineStatus;
};
