/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Maas tag
 */
export type MaasTag = {
  /** Comment on Maas tag */
  comment?: string;
  /** Definition of Maas tag */
  definition?: string;
  /** Kernel Opts on Maas tag */
  kernelOpts?: string;
  /** Name of Maas tag */
  name?: string;
  /** Description of Maas tag */
  resourceUri?: string;
};
