/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { CloudRate } from './cloudRate';

/**
 * Machine pool estimated rate information
 */
export type MachinePoolRate = {
  name?: string;
  nodesCount?: number;
  rate?: CloudRate;
};
