/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterProfileTemplateMeta } from './clusterProfileTemplateMeta';

export type MachinePoolMeta = {
  cloudType?: string;
  /** number of healthy machines */
  healthy?: number;
  infraProfileTemplate?: ClusterProfileTemplateMeta;
  /** whether this pool is for control plane */
  isControlPlane?: boolean;
  /** labels for this pool, example: control-plane/worker, gpu, windows */
  labels?: string[];
  /** number of machines under maintenance */
  maintenanceMode?: number;
  /** size of the pool, number of machines */
  size?: number;
};
