/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MachineCertificate } from './machineCertificate';

/**
 * K8 Certificates for all the cluster's control plane nodes
 */
export type MachineCertificates = {
  machineCertificates?: MachineCertificate[];
};
