/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Manifest object
 */
export type ManifestSummary = {
  /** Manifest content in yaml */
  content?: string;
  /** Manifest digest */
  digest?: string;
  /** Manifest name */
  name?: string;
  /** Manifest uid */
  uid?: string;
};
