/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ManifestData } from './manifestData';

/**
 * Manifest spec
 */
export type ManifestSpec = {
  draft?: ManifestData;
  published?: ManifestData;
};
