/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type MfaConveyancePreference = typeof MfaConveyancePreference[keyof typeof MfaConveyancePreference];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MfaConveyancePreference = {
  none: 'none',
  indirect: 'indirect',
  direct: 'direct',
  enterprise: 'enterprise',
} as const;
