/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MfaConveyancePreference } from './mfaConveyancePreference';
import type { MfaAuthenticatorSelection } from './mfaAuthenticatorSelection';
import type { MfaCredentialDescriptor } from './mfaCredentialDescriptor';
import type { MfaAuthenticationExtensions } from './mfaAuthenticationExtensions';
import type { MfaCredentialParameter } from './mfaCredentialParameter';
import type { MfaRelyingPartyEntity } from './mfaRelyingPartyEntity';
import type { MfaUserEntity } from './mfaUserEntity';

export type MfaPublicKeyCredentialCreationOptions = {
  attestation?: MfaConveyancePreference;
  authenticatorSelection?: MfaAuthenticatorSelection;
  challenge?: string;
  excludeCredentials?: MfaCredentialDescriptor[];
  extensions?: MfaAuthenticationExtensions;
  pubKeyCredParams?: MfaCredentialParameter[];
  rp?: MfaRelyingPartyEntity;
  timeout?: number;
  user?: MfaUserEntity;
};
