/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { MgmtAppObjectStatusPods } from './mgmtAppObjectStatusPods';

export type MgmtAppObjectStatus = {
  availableReplicas?: number;
  creationTime?: Time;
  desiredReplicaCount?: number;
  isHealthy?: boolean;
  messages?: string[];
  name?: string;
  pods?: MgmtAppObjectStatusPods;
};
