/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { MgmtErrSpecDebug } from './mgmtErrSpecDebug';
import type { MgmtErrSpecUserCtx } from './mgmtErrSpecUserCtx';

export type MgmtErrSpec = {
  causes?: string[];
  data?: string;
  debug?: MgmtErrSpecDebug;
  errCode?: string;
  errMsg?: string;
  stackTraces?: string[];
  userCtx?: MgmtErrSpecUserCtx;
};
