/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MgmtAppNameSpaceStatusCronJobs } from './mgmtAppNameSpaceStatusCronJobs';
import type { MgmtAppNameSpaceStatusDeployments } from './mgmtAppNameSpaceStatusDeployments';
import type { MgmtAppNameSpaceStatusStatefulSets } from './mgmtAppNameSpaceStatusStatefulSets';

export type MgmtAppNameSpaceStatus = {
  cronJobs?: MgmtAppNameSpaceStatusCronJobs;
  deployments?: MgmtAppNameSpaceStatusDeployments;
  isHealthy?: boolean;
  messages?: string[];
  statefulSets?: MgmtAppNameSpaceStatusStatefulSets;
};
