/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MgmtFileTransferFtpEntity } from './mgmtFileTransferFtpEntity';

/**
 * delete backups based on retention period
 */
export type MgmtDeleteBackupFtpEntity = {
  fileTransferConfig?: MgmtFileTransferFtpEntity;
  retentionPeriod?: number;
};
