/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { MgmtBackupSpecScheduleType } from './mgmtBackupSpecScheduleType';

/**
 * backup spec
 */
export type MgmtBackupSpec = {
  backupUid?: string;
  mode?: string;
  modeUid?: string;
  /** proxy information if applicable */
  proxy?: string;
  scheduleTime?: Time;
  scheduleType?: MgmtBackupSpecScheduleType;
};
