/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MgmtDbCollectionInfo } from './mgmtDbCollectionInfo';

/**
 * Database info
 */
export type MgmtDbInfo = {
  collections?: MgmtDbCollectionInfo[];
  isEmpty?: boolean;
  name?: string;
  size?: number;
  totalIndexSize?: number;
};
