/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { MgmtAppUpgradeSpec } from './mgmtAppUpgradeSpec';
import type { MgmtAppUpgradeStatus } from './mgmtAppUpgradeStatus';

export type MgmtAppUpgrade = {
  spec?: MgmtAppUpgradeSpec;
  status?: MgmtAppUpgradeStatus;
};
