/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type MgmtBackupSpecScheduleType = typeof MgmtBackupSpecScheduleType[keyof typeof MgmtBackupSpecScheduleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MgmtBackupSpecScheduleType = {
  OnDemand: 'OnDemand',
  Automated: 'Automated',
} as const;
