/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { NonFipsConfigMode } from './nonFipsConfigMode';

/**
 * Non-FIPS configuration
 */
export type NonFipsConfig = {
  /** enable or disable the non FIPS complaint */
  mode?: NonFipsConfigMode;
};
