/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Describes action type for the notification. Possible Values [NotifyActionPacksUpdate, NotifyActionClusterProfileUpdate, NotifyActionPackRegistryUpdate, NotifyActionClusterUpdate, NotifyActionNone]
 */
export type NotificationActionActionType = typeof NotificationActionActionType[keyof typeof NotificationActionActionType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationActionActionType = {
  NotifyActionPacksUpdate: 'NotifyActionPacksUpdate',
  NotifyActionClusterProfileUpdate: 'NotifyActionClusterProfileUpdate',
  NotifyActionPackRegistryUpdate: 'NotifyActionPackRegistryUpdate',
  NotifyActionClusterUpdate: 'NotifyActionClusterUpdate',
  NotifyActionNone: 'NotifyActionNone',
} as const;
