/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMetaUpdateEntityAnnotations } from './objectMetaUpdateEntityAnnotations';
import type { ObjectMetaUpdateEntityLabels } from './objectMetaUpdateEntityLabels';

/**
 * ObjectMeta update entity with uid as input
 */
export type ObjectMetaUpdateEntity = {
  annotations?: ObjectMetaUpdateEntityAnnotations;
  labels?: ObjectMetaUpdateEntityLabels;
  name?: string;
  uid?: string;
};
