/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { OidcAuthorizationTokenResponseRaw } from './oidcAuthorizationTokenResponseRaw';

export type OidcAuthorizationTokenResponse = {
  access_token?: string;
  error?: string;
  error_description?: string;
  expires_in?: number;
  id_token?: string;
  raw?: OidcAuthorizationTokenResponseRaw;
  refresh_token?: string;
  scope?: string;
};
