/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SsoLogin } from './ssoLogin';
import type { OidcLoginsTenantLogin } from './oidcLoginsTenantLogin';

/**
 * loginsDetails
 */
export type OidcLogins = {
  systemLogins?: SsoLogin[];
  tenantLogin?: OidcLoginsTenantLogin;
};
