/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { OpenStackResource } from './openStackResource';

/**
 * Cluster level configuration for OpenStack cloud and applicable for all the machine pools
 */
export type OpenStackClusterConfig = {
  /** Create bastion node option we have earlier supported creation of bastion by default */
  bastionDisabled?: boolean;
  /** DNSNameservers is the list of nameservers for OpenStack Subnet being created. Set this value when you need create a new network/subnet while the access through DNS is required. */
  dnsNameservers?: string[];
  domain?: OpenStackResource;
  network?: OpenStackResource;
  /** For dynamic provision NodeCIDR is the OpenStack Subnet to be created. Cluster actuator will create a network, a subnet with NodeCIDR, and a router connected to this subnet. If you leave this empty, no network will be created. */
  nodeCidr?: string;
  project?: OpenStackResource;
  region?: string;
  sshKeyName?: string;
  subnet?: OpenStackResource;
};
