/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * OpenStack subnet entity
 */
export type OpenStackSubnet = {
  /** Description for the network */
  description?: string;
  /** UUID for the network */
  id?: string;
  /** Human-readable name for the network. Might not be unique */
  name?: string;
};
