/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { OpenStackSubnet } from './openStackSubnet';

/**
 * OpenStack network
 */
export type OpenStackNetwork = {
  /** Description of OpenStack network */
  description?: string;
  /** Id of OpenStack network */
  id?: string;
  /** Name of OpenStack network */
  name?: string;
  /** Subnets associated with OpenStack network */
  subnets?: OpenStackSubnet[];
};
