/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { GenericInstanceType } from './genericInstanceType';
import type { OpenStackNic } from './openStackNic';

/**
 * OpenStack cloud VM definition spec
 */
export type OpenStackMachineSpec = {
  az?: string;
  image?: string;
  instanceType: GenericInstanceType;
  nics: OpenStackNic[];
  projectId?: string;
  securityGroups?: string[];
  sshKeyName?: string;
};
