/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * OpenStack region entity
 */
export type OpenStackRegion = {
  /** Description of OpenStack region */
  description?: string;
  /** Id of OpenStack region */
  id?: string;
  /** Parent region id of OpenStack region */
  parentRegionId?: string;
};
