/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * OpenStack keypair. KeyPair is an SSH key known to the OpenStack Cloud that is available to be injected into servers
 */
export type OpenStackKeypair = {
  /** Name is used to refer to this keypair from other services within this region */
  name?: string;
  /** PublicKey is the public key from this pair, in OpenSSH format */
  publicKey?: string;
};
