/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { OpenStackMachinePoolCloudConfigEntity } from './openStackMachinePoolCloudConfigEntity';
import type { MachinePoolConfigEntity } from './machinePoolConfigEntity';

export type OpenStackMachinePoolConfigEntity = {
  cloudConfig: OpenStackMachinePoolCloudConfigEntity;
  poolConfig?: MachinePoolConfigEntity;
};
