/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * OpenStack domain. A Domain is a collection of projects, users, and roles
 */
export type OpenStackDomain = {
  /** Description is the description of the Domain */
  description?: string;
  /** ID is the unique ID of the domain */
  id?: string;
  /** Name is the name of the domain */
  name?: string;
};
