/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterCondition } from './clusterCondition';

/**
 * OpenStackCloudConfigStatus defines the observed state of OpenStackCloudConfig The cloudimage info built by Mold is stored here image should be mapped to a specific machinepool
 */
export type OpenStackCloudConfigStatus = {
  conditions?: ClusterCondition[];
  nodeImage?: string;
  /** sourceImageId, it can be from packref's annotations or from pack.json */
  sourceImageId?: string;
  useCapiImage?: boolean;
};
