/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectReference } from './objectReference';
import type { OpenStackClusterConfig } from './openStackClusterConfig';
import type { OpenStackMachinePoolConfig } from './openStackMachinePoolConfig';

/**
 * OpenStackCloudConfigSpec defines the cloud configuration input by user This will translate to clusterspec/machinespec for cluster-api
 */
export type OpenStackCloudConfigSpec = {
  cloudAccountRef?: ObjectReference;
  clusterConfig?: OpenStackClusterConfig;
  machinePoolConfig?: OpenStackMachinePoolConfig[];
};
