/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { OpenStackMachinePoolConfigAdditionalLabels } from './openStackMachinePoolConfigAdditionalLabels';
import type { OpenStackMachinePoolConfigAdditionalTags } from './openStackMachinePoolConfigAdditionalTags';
import type { OpenstackFlavorConfig } from './openstackFlavorConfig';
import type { MachinePoolProperties } from './machinePoolProperties';
import type { OpenStackResource } from './openStackResource';
import type { Taint } from './taint';
import type { UpdateStrategy } from './updateStrategy';

export type OpenStackMachinePoolConfig = {
  /** additionalLabels */
  additionalLabels?: OpenStackMachinePoolConfigAdditionalLabels;
  /** AdditionalTags is an optional set of tags to add to resources managed by the provider, in addition to the ones added by default. For eg., tags for EKS nodeGroup or EKS NodegroupIAMRole */
  additionalTags?: OpenStackMachinePoolConfigAdditionalTags;
  /** for control plane pool, this will be the failure domains for kcp */
  azs?: string[];
  /** DiskGiB is used to configure rootVolume, the volume metadata to boot from */
  diskGiB?: number;
  /** Openstack flavor name, only return argument */
  flavor?: string;
  flavorConfig: OpenstackFlavorConfig;
  image?: string;
  /** whether this pool is for control plane */
  isControlPlane?: boolean;
  /** labels for this pool, example: control-plane/worker, gpu, windows */
  labels?: string[];
  machinePoolProperties?: MachinePoolProperties;
  /** max size of the pool, for scaling */
  maxSize?: number;
  /** min size of the pool, for scaling */
  minSize?: number;
  name?: string;
  /** Minimum number of seconds a node should be Ready, before the next node is selected for repave. Applicable only for workerpools in infrastructure cluster */
  nodeRepaveInterval?: number;
  /** size of the pool, number of machines */
  size?: number;
  subnet?: OpenStackResource;
  /** control plane or worker taints */
  taints?: Taint[];
  updateStrategy?: UpdateStrategy;
  /** if IsControlPlane==true && useControlPlaneAsWorker==true, then will remove control plane taint this will not be used for worker pools */
  useControlPlaneAsWorker?: boolean;
};
