/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type OpenstackFlavorConfig = {
  /** DiskGiB is the size of a virtual machine's disk, in GiB. */
  diskGiB?: number;
  /** MemoryMiB is the size of a virtual machine's memory, in MiB. */
  memoryMiB?: number;
  /** Openstack flavor name */
  name: string;
  /** NumCPUs is the number of virtual processors in a virtual machine. */
  numCPUs?: number;
};
