/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * OpenStack flavor entity. Flavor represent (virtual) hardware configurations for server resources
 */
export type OpenStackFlavor = {
  /** Disk is the amount of root disk, measured in GB */
  disk?: number;
  /** Ephemeral is the amount of ephemeral disk space, measured in GB */
  ephemeral?: number;
  /** ID is the flavor's unique ID */
  id?: string;
  /** Amount of memory, measured in MB */
  memory?: number;
  /** Name is the name of the flavor */
  name?: string;
  /** VCPUs indicates how many (virtual) CPUs are available for this flavor */
  vcpus?: number;
};
