/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { OpenStackDomain } from './openStackDomain';
import type { OpenStackRegion } from './openStackRegion';

/**
 * List of OpenStack regions and domains
 */
export type OpenStackRegions = {
  /** List of OpenStack domains */
  domains: OpenStackDomain[];
  /** List of OpenStack regions */
  regions: OpenStackRegion[];
};
