/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { MaasCloudAccount } from './maasCloudAccount';

export type OverlordMaasAccountCreate = {
  account?: MaasCloudAccount;
  /** Name for the private gateway & cloud account */
  name?: string;
  shareWithProjects?: boolean;
};
