/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VsphereOverlordClusterConfigEntity } from './vsphereOverlordClusterConfigEntity';
import type { SpectroClusterProfileEntity } from './spectroClusterProfileEntity';
import type { ClusterConfigEntity } from './clusterConfigEntity';

export type OverlordVsphereCloudConfig = {
  clusterConfig?: VsphereOverlordClusterConfigEntity;
  /** Cluster profiles pack configuration for private gateway cluster */
  clusterProfiles?: SpectroClusterProfileEntity[];
  clusterSettings?: ClusterConfigEntity;
  /** size of the pool, number of machines */
  size?: number;
};
