/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type OverlordsPairingCodeCloudType = typeof OverlordsPairingCodeCloudType[keyof typeof OverlordsPairingCodeCloudType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OverlordsPairingCodeCloudType = {
  vsphere: 'vsphere',
  openstack: 'openstack',
  maas: 'maas',
  'apache-cloudstack': 'apache-cloudstack',
} as const;
