/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { OverloadSpec } from './overloadSpec';
import type { OverloadStatus } from './overloadStatus';

/**
 * Overlord defintiion
 */
export type Overlord = {
  kind?: string;
  metadata?: ObjectMeta;
  spec?: OverloadSpec;
  status?: OverloadStatus;
};
