/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ManifestRefUpdateEntity } from './manifestRefUpdateEntity';
import type { PackType } from './packType';

/**
 * Pack input entity with values to overwrite and manifests for the intial creation
 */
export type PackManifestUpdateEntity = {
  /** Pack layer */
  layer?: string;
  /** Pack manifests are additional content as part of the profile */
  manifests?: ManifestRefUpdateEntity[];
  /** Pack name */
  name: string;
  /** Pack registry uid */
  registryUid?: string;
  /** Pack tag */
  tag?: string;
  type?: PackType;
  /** Pack uid */
  uid?: string;
  /** Pack values represents the values.yaml used as input parameters either Params OR Values should be used, not both If both applied at the same time, will only use Values */
  values?: string;
};
