/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Pack template dependency
 */
export type PackDependency = {
  /** Pack template dependency pack layer */
  layer?: string;
  /** Pack template dependency pack name */
  name?: string;
  /** If true then dependency pack values can't be overridden */
  readOnly?: boolean;
};
