/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Annotations is used to allow packref to add more arbitrary information one example is to add git reference for values.yaml
 */
export type PackRefAnnotations = {[key: string]: string};
