/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PackResolvedValues } from './packResolvedValues';
import type { PackSummarySpec } from './packSummarySpec';
import type { RegistryMetadata } from './registryMetadata';

/**
 * Pack summary spec
 */
export type PackRefSummarySpec = {
  macros?: PackResolvedValues;
  pack?: PackSummarySpec;
  registry?: RegistryMetadata;
};
