/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Pack manifest import objct
 */
export type PackManifestImportEntity = {
  /** Pack manifest content in yaml */
  content?: string;
  /** Pack manifest name */
  name?: string;
};
