/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type PacksNameRegistryUidListParams = {
/**
 * Pack cloud type
 */
cloudType?: string;
/**
 * Pack layer
 */
layer?: string;
/**
 * Comma seperated pack states. Example values are "deprecated" "deprecated,disabled". If states is not specified or empty then by default API will return all packs except "disabled" packs
 */
states?: string;
};
