/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { PackDependency } from './packDependency';

/**
 * Pack template parameter option
 */
export type PackTemplateParameterOption = {
  /** Pack template parameter dependencies */
  dependencies?: PackDependency[];
  /** Pack template parameter description */
  description?: string;
  /** Pack template parameter label */
  label?: string;
};
