/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PackTemplateParameterOptions } from './packTemplateParameterOptions';

/**
 * Pack template parameter
 */
export type PackTemplateParameter = {
  /** Pack template parameter description */
  description?: string;
  /** Pack template parameter display name */
  displayName?: string;
  /** Pack template parameter format */
  format?: string;
  /** Pack template parameter hidden flag, if true then the parameter is hidden in the UI */
  hidden?: boolean;
  /** Pack template parameter list options as string array */
  listOptions?: string[];
  /** Pack template parameter name */
  name?: string;
  /** Pack template parameter optional flag, if true then the parameter value is not mandatory */
  optional?: boolean;
  /** Pack template parameter options array */
  options?: PackTemplateParameterOptions;
  /** Pack template parameter readonly flag, if true then the parameter value can't be overridden */
  readOnly?: boolean;
  /** Pack template parameter regex, if set then parameter value must match with specified regex */
  regex?: string;
  /** Pack template parameter target key which is mapped to the key defined in the pack values */
  targetKey?: string;
  /** Pack template parameter data type */
  type?: string;
  /** Pack template parameter value */
  value?: string;
};
