/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Pack manifest import objct
 */
export type PackManifestImportEntity = {
  /** Pack manifest content in yaml */
  content?: string;
  /** Pack manifest name */
  name?: string;
};
