/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ManifestInputEntity } from './manifestInputEntity';
import type { PackType } from './packType';

/**
 * Pack request payload
 */
export type PackManifestEntity = {
  /** Pack layer */
  layer?: string;
  /** Pack manifests are additional content as part of the profile */
  manifests?: ManifestInputEntity[];
  /** Pack name */
  name: string;
  /** Pack registry uid */
  registryUid?: string;
  /** Pack tag */
  tag?: string;
  type?: PackType;
  /** Pack uid */
  uid?: string;
  /** Pack values represents the values.yaml used as input parameters either Params OR Values should be used, not both If both applied at the same time, will only use Values */
  values?: string;
};
