/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { PackRegistrySummary } from './packRegistrySummary';
import type { ListMetaData } from './listMetaData';

/**
 * Pack Registries Summary
 */
export type PackRegistriesSummary = {
  items: PackRegistrySummary[];
  listmeta?: ListMetaData;
};
