/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { RegistryAuth } from './registryAuth';

/**
 * Pack registry credentials spec
 */
export type PackRegistrySpec = {
  auth: RegistryAuth;
  endpoint: string;
  name?: string;
  private?: boolean;
  /** Pack registry uid */
  registryUid?: string;
  scope?: string;
};
