/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * type of the pack
 */
export type PackRefType = typeof PackRefType[keyof typeof PackRefType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackRefType = {
  spectro: 'spectro',
  helm: 'helm',
  manifest: 'manifest',
  oci: 'oci',
} as const;
