/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type PackRefLayer = typeof PackRefLayer[keyof typeof PackRefLayer];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackRefLayer = {
  kernel: 'kernel',
  os: 'os',
  k8s: 'k8s',
  cni: 'cni',
  csi: 'csi',
  addon: 'addon',
} as const;
