/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { PackSummarySpec } from './packSummarySpec';
import type { PackSummaryStatus } from './packSummaryStatus';

/**
 * Pack summary object
 */
export type PackSummary = {
  /** Pack api version */
  apiVersion?: string;
  /** Pack kind */
  kind?: string;
  metadata?: ObjectMeta;
  spec?: PackSummarySpec;
  status?: PackSummaryStatus;
};
