/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Pack dependency metadata
 */
export type PackDependencyMeta = {
  /** Pack display name */
  displayName?: string;
  /** Pack logo url */
  logoUrl?: string;
  /** Pack name */
  name?: string;
  /** Pack registry uid */
  registryUid?: string;
  /** Pack uid */
  uid?: string;
  /** Pack version */
  version?: string;
};
