/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Packs sort by fields
 * @nullable
 */
export type PackSortFields = typeof PackSortFields[keyof typeof PackSortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PackSortFields = {
  name: 'name',
  type: 'type',
  layer: 'layer',
  addOnType: 'addOnType',
  displayName: 'displayName',
} as const;
