/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Card } from './card';

/**
 * Payment method object
 */
export type PaymentMethod = {
  card?: Card;
  /** Customer uid */
  customerId?: string;
  /** First name of the user */
  firstName?: string;
  /** Last name of the user */
  lastName?: string;
  /** Payment method uid */
  paymentMethodId?: string;
};
