/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type PermissionsListScope = typeof PermissionsListScope[keyof typeof PermissionsListScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PermissionsListScope = {
  system: 'system',
  tenant: 'tenant',
  project: 'project',
  resource: 'resource',
} as const;
