/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { PlanCreditEntityType } from './planCreditEntityType';

/**
 * Plan Credit entity for create/update request
 */
export type PlanCreditEntity = {
  cpuCoreHours?: number;
  expiry?: Time;
  name?: string;
  start?: Time;
  type: PlanCreditEntityType;
};
