/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PlanLimitSpec } from './planLimitSpec';

/**
 * Monthly Plan Limit
 */
export type PlanLimit = {
  alloy?: PlanLimitSpec;
  /** is onDemand plan and has no limit */
  isOnDemand?: boolean;
  /** is unlimited cpu core hours */
  isUnlimited?: boolean;
  pure?: PlanLimitSpec;
};
