/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type PlanSpecType = typeof PlanSpecType[keyof typeof PlanSpecType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlanSpecType = {
  Trial: 'Trial',
  MonthlyOnDemand: 'MonthlyOnDemand',
  AnnualSubscription: 'AnnualSubscription',
} as const;
