/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type PlanChangeUpdateType = typeof PlanChangeUpdateType[keyof typeof PlanChangeUpdateType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PlanChangeUpdateType = {
  Trial: 'Trial',
  MonthlyOnDemand: 'MonthlyOnDemand',
  AnnualSubscription: 'AnnualSubscription',
} as const;
