/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ResourceUsage } from './resourceUsage';
import type { Time } from './time';
import type { PlanLimit } from './planLimit';
import type { PlanMonthlyUsagePlanType } from './planMonthlyUsagePlanType';
import type { TotalResourceUsage } from './totalResourceUsage';

/**
 * Plan monthly usage entity
 */
export type PlanMonthlyUsage = {
  dailyUsages?: ResourceUsage[];
  month?: Time;
  planLimit?: PlanLimit;
  planType?: PlanMonthlyUsagePlanType;
  planUid?: string;
  totalMonthlyUsage?: TotalResourceUsage;
};
