/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Nameserver } from './nameserver';

/**
 * Pool defines IP ranges or with CIDR for available IPs Gateway, Prefix and Nameserver if provided, will overwrite values in IPPool
 */
export type Pool = {
  /** End is the last IP address that can be rendered. It is used as a validation that the rendered IP is in bound. */
  end?: string;
  /** Gateway is the gateway ip address */
  gateway?: string;
  nameserver?: Nameserver;
  /** Prefix is the mask of the network as integer (max 128) */
  prefix?: number;
  /** Start is the first ip address that can be rendered */
  start?: string;
  /** Subnet is used to validate that the rendered IP is in bounds. eg: 192.168.0.0/24 If Start value is not given, start value is derived from the subnet ip incremented by 1 (start value is `192.168.0.1` for subnet `192.168.0.0/24`) */
  subnet?: string;
};
