/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PackRefSummary } from './packRefSummary';

/**
 * Edge host clusterprofile template summary
 */
export type ProfileTemplateSummary = {
  cloudType?: string;
  name?: string;
  packs?: PackRefSummary[];
  type?: string;
  uid?: string;
  version?: string;
};
