/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type ProfileType = typeof ProfileType[keyof typeof ProfileType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProfileType = {
  cluster: 'cluster',
  infra: 'infra',
  'add-on': 'add-on',
  system: 'system',
} as const;
