/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { TeamRoleMap } from './teamRoleMap';
import type { UserRoleMap } from './userRoleMap';

/**
 * Project specifications
 */
export type ProjectEntitySpec = {
  logoUid?: string;
  teams?: TeamRoleMap[];
  users?: UserRoleMap[];
};
