/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Project cleanup status
 */
export type ProjectCleanUpStatus = {
  cleanedResources?: string[];
  msg?: string;
  state?: string;
};
