/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Project alert component
 */
export type ProjectAlertComponent = {
  description?: string;
  name?: string;
  supportedChannels?: string[];
};
