/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Alert } from './alert';
import type { TeamRoleMap } from './teamRoleMap';
import type { UserRoleMap } from './userRoleMap';

/**
 * Project specifications
 */
export type ProjectSpec = {
  alerts?: Alert[];
  logoUrl?: string;
  teams?: TeamRoleMap[];
  users?: UserRoleMap[];
};
