/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { RegistryAuth } from './registryAuth';

/**
 * Registry configuration
 */
export type RegistryConfiguration = {
  auth?: RegistryAuth;
  endpoint?: string;
  name?: string;
};
