/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type RegistriesHelmCreateScope = typeof RegistriesHelmCreateScope[keyof typeof RegistriesHelmCreateScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegistriesHelmCreateScope = {
  system: 'system',
  tenant: 'tenant',
  all: 'all',
} as const;
