/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type RegistriesMetadataScope = typeof RegistriesMetadataScope[keyof typeof RegistriesMetadataScope];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegistriesMetadataScope = {
  system: 'system',
  tenant: 'tenant',
  all: 'all',
} as const;
