/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type RegistryAuthType = typeof RegistryAuthType[keyof typeof RegistryAuthType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegistryAuthType = {
  noAuth: 'noAuth',
  basic: 'basic',
  token: 'token',
} as const;
