/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type RelatedObjectKind = typeof RelatedObjectKind[keyof typeof RelatedObjectKind];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RelatedObjectKind = {
  spectrocluster: 'spectrocluster',
  machine: 'machine',
  cloudconfig: 'cloudconfig',
  clusterprofile: 'clusterprofile',
  pack: 'pack',
  appprofile: 'appprofile',
  appdeployment: 'appdeployment',
  edgehost: 'edgehost',
} as const;
