/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { ReleaseDescription } from './releaseDescription';

/**
 * spectro application management release version information
 */
export type ReleaseVersion = {
  date?: Time;
  description?: string;
  releaseNotes?: ReleaseDescription[];
  version?: string;
};
