/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ResourceCostSummaryOptionsGroupBy } from './resourceCostSummaryOptionsGroupBy';

/**
 * Resource cost summary options
 */
export type ResourceCostSummaryOptions = {
  enableSummaryView?: boolean;
  groupBy?: ResourceCostSummaryOptionsGroupBy;
  period?: number;
};
