/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ResourceReference } from './resourceReference';
import type { ResourceCostDataPoint } from './resourceCostDataPoint';
import type { ResourceTotalCost } from './resourceTotalCost';

/**
 * Resource cost summary information
 */
export type ResourceCostSummary = {
  associatedResources?: ResourceReference[];
  data?: ResourceCostDataPoint[];
  entity?: ResourceReference;
  total?: ResourceTotalCost;
};
