/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';
import type { ResourceWorkloadFilter } from './resourceWorkloadFilter';

/**
 * Resource usage summary filter
 */
export type ResourceUsageSummaryFilter = {
  clouds?: string[];
  clusters?: string[];
  endTime?: Time;
  includeControlPlaneMachines?: boolean;
  /** Deprecated. Use includeControlPlaneMachines */
  includeMasterMachines?: boolean;
  namespaces?: string[];
  pods?: string[];
  projects?: string[];
  startTime?: Time;
  workload?: ResourceWorkloadFilter;
  workspaces?: string[];
};
