/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ProjectResourceUsage } from './projectResourceUsage';
import type { Time } from './time';

/**
 * ResourceUsage
 */
export type ResourceUsage = {
  projects?: ProjectResourceUsage[];
  timestamp?: Time;
  totalAlloyCpuCoreHours?: number;
  totalPureCpuCoreHours?: number;
};
