/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ResourceReference } from './resourceReference';
import type { ResourceConsumptionDataPoint } from './resourceConsumptionDataPoint';
import type { ResourceTotalConsumptionData } from './resourceTotalConsumptionData';

/**
 * Resource consumption information
 */
export type ResourceConsumption = {
  associatedResources?: ResourceReference[];
  data?: ResourceConsumptionDataPoint[];
  entity?: ResourceReference;
  total?: ResourceTotalConsumptionData;
};
