/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type ResourceUsageSummaryOptionsGroupBy = typeof ResourceUsageSummaryOptionsGroupBy[keyof typeof ResourceUsageSummaryOptionsGroupBy];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceUsageSummaryOptionsGroupBy = {
  tenant: 'tenant',
  project: 'project',
  workspace: 'workspace',
  cluster: 'cluster',
  namespace: 'namespace',
  deployment: 'deployment',
  statefulset: 'statefulset',
  daemonset: 'daemonset',
  pod: 'pod',
  cloud: 'cloud',
} as const;
