/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type ResourceLimitType = typeof ResourceLimitType[keyof typeof ResourceLimitType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResourceLimitType = {
  user: 'user',
  project: 'project',
  apiKey: 'apiKey',
  team: 'team',
  role: 'role',
  cloudaccount: 'cloudaccount',
  clusterprofile: 'clusterprofile',
  workspace: 'workspace',
  registry: 'registry',
  privategateway: 'privategateway',
  location: 'location',
  certificate: 'certificate',
  macro: 'macro',
  sshkey: 'sshkey',
  alert: 'alert',
  spectrocluster: 'spectrocluster',
  edgehost: 'edgehost',
  appprofile: 'appprofile',
  appdeployment: 'appdeployment',
  edgetoken: 'edgetoken',
  clustergroup: 'clustergroup',
  filter: 'filter',
  systemadmin: 'systemadmin',
} as const;
