/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { RoleSpec } from './roleSpec';
import type { RoleStatus } from './roleStatus';

/**
 * Role
 */
export type Role = {
  metadata?: ObjectMeta;
  spec?: RoleSpec;
  status?: RoleStatus;
};
