/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsCloudAccount } from './awsCloudAccount';

/**
 * S3 storage config object
 */
export type S3StorageConfig = {
  /** S3 storage bucket name */
  bucketName: string;
  /** CA Certificate */
  caCert?: string;
  credentials: AwsCloudAccount;
  /** AWS region name */
  region: string;
  s3ForcePathStyle?: boolean;
  /** Custom hosted S3 URL */
  s3Url?: string;
  /** Set to 'true', to use Restic plugin for the backup */
  useRestic?: boolean;
};
