/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { SchedulerJobSpec } from './schedulerJobSpec';
import type { SchedulerJobStatus } from './schedulerJobStatus';

export type SchedulerJob = {
  metadata?: ObjectMeta;
  spec?: SchedulerJobSpec;
  status?: SchedulerJobStatus;
};
