/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SearchFilterConjunctionOperator } from './searchFilterConjunctionOperator';
import type { SearchFilterItem } from './searchFilterItem';

export type SearchFilterGroup = {
  conjunction?: SearchFilterConjunctionOperator;
  filters?: SearchFilterItem[];
};
