/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SearchFilterSchemaSpecEnumValue } from './searchFilterSchemaSpecEnumValue';

export type SearchFilterSchemaSpecProperty = {
  default?: string;
  displayName?: string;
  enum?: string[];
  enumValues?: SearchFilterSchemaSpecEnumValue[];
  hideDisplay?: boolean;
  isDeprecated?: boolean;
  maxFloatVal?: number;
  maxIntVal?: number;
  minFloatVal?: number;
  minIntVal?: number;
  name?: string;
  type?: string;
};
