/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SearchFilterCondition } from './searchFilterCondition';
import type { SearchFilterPropertyType } from './searchFilterPropertyType';

export type SearchFilterItem = {
  condition?: SearchFilterCondition;
  property?: string;
  type?: SearchFilterPropertyType;
};
