/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type SearchFilterDateOperator = typeof SearchFilterDateOperator[keyof typeof SearchFilterDateOperator];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchFilterDateOperator = {
  eq: 'eq',
  gt: 'gt',
  gte: 'gte',
  lt: 'lt',
  lte: 'lte',
  range: 'range',
} as const;
