/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SearchFilterIntegerConditionMatch } from './searchFilterIntegerConditionMatch';
import type { SearchFilterIntegerOperator } from './searchFilterIntegerOperator';

export type SearchFilterIntegerCondition = {
  match?: SearchFilterIntegerConditionMatch;
  negation?: boolean;
  operator?: SearchFilterIntegerOperator;
};
