/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Returns the data encryption key for the session
 */
export type ServiceEncryptionKey = {
  /** Encryption key to be used to decrypt the encrypted data in the response */
  encryptionKey?: string;
};
