/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type ServiceManifestGetAction = typeof ServiceManifestGetAction[keyof typeof ServiceManifestGetAction];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceManifestGetAction = {
  apply: 'apply',
  delete: 'delete',
  resources: 'resources',
} as const;
