/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SonobuoyLogEntity } from './sonobuoyLogEntity';

/**
 * Sonobuoy report
 */
export type SonobuoyReportEntity = {
  fail?: number;
  logs?: SonobuoyLogEntity[];
  node?: string;
  pass?: number;
  plugin?: string;
  status?: string;
  total?: number;
};
