/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SpcApplyActionType } from './spcApplyActionType';
import type { Time } from './time';

export type SpcApply = {
  actionType?: SpcApplyActionType;
  /** If it is true then Agent can apply the changes to the palette */
  canBeApplied?: boolean;
  crdDigest?: string;
  lastModifiedTime?: Time;
  patchAppliedTime?: Time;
  spcHash?: string;
  spcInfraHash?: string;
};
