/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { FilterString } from './filterString';
import type { SpcPolicyType } from './spcPolicyType';
import type { FilterArray } from './filterArray';

/**
 * Spc policy filter spec
 */
export type SpcPolicyFilterSpec = {
  policyName?: FilterString;
  policyType?: SpcPolicyType[];
  tags?: FilterArray;
};
