/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type SpcPolicySortFields = typeof SpcPolicySortFields[keyof typeof SpcPolicySortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpcPolicySortFields = {
  policyName: 'policyName',
  policyType: 'policyType',
  creationTimestamp: 'creationTimestamp',
  lastModifiedTimestamp: 'lastModifiedTimestamp',
} as const;
