/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type SpcPolicyMetadata = {
  /** The kind of the spc policy eg maintenance. */
  kind?: string;
  /** The name of the spc policy */
  name?: string;
  /** The project UID of the spc policy */
  projectUid?: string;
  /** The UID of the spc policy */
  uid?: string;
};
