/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SpectroClusterPackCondition } from './spectroClusterPackCondition';
import type { Time } from './time';
import type { PackType } from './packType';

export type SpectroClusterPackStatusEntity = {
  condition?: SpectroClusterPackCondition;
  endTime?: Time;
  /** Pack name */
  name?: string;
  /** Cluster profile uid */
  profileUid?: string;
  startTime?: Time;
  type?: PackType;
  /** pack version */
  version?: string;
};
