/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { MachinePoolRate } from './machinePoolRate';
import type { TotalClusterRate } from './totalClusterRate';
import type { CloudResourceMetadata } from './cloudResourceMetadata';

/**
 * Cluster estimated rate information
 */
export type SpectroClusterRate = {
  machinePools?: MachinePoolRate[];
  name?: string;
  rate?: TotalClusterRate;
  resourceMetadata?: CloudResourceMetadata;
};
