/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { PackValuesEntity } from './packValuesEntity';
import type { SpectroClusterVariable } from './spectroClusterVariable';

/**
 * Cluster profile request payload
 */
export type SpectroClusterProfileEntity = {
  /** Cluster profile packs array */
  packValues?: PackValuesEntity[];
  /** Cluster profile uid to be replaced with new profile */
  replaceWithProfile?: string;
  /** Cluster profile uid */
  uid?: string;
  variables?: SpectroClusterVariable[];
};
