/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SpectroClusterVariableResponse } from './spectroClusterVariableResponse';

/**
 * List of cluster variables with schema belonging to a cluster
 */
export type SpectroClusterVariables = {
  /** Profile uid to which the cluster variable belongs */
  profileUid: string;
  /** List of cluster variables with schema */
  variables?: SpectroClusterVariableResponse[];
};
