/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SpectroClusterMetaSummarySpecSummaryArchTypeItem } from './spectroClusterMetaSummarySpecSummaryArchTypeItem';
import type { ClusterMetaSpecLocation } from './clusterMetaSpecLocation';
import type { ProjectMeta } from './projectMeta';

/**
 * Spectro cluster meta summary
 */
export type SpectroClusterMetaSummarySpecSummary = {
  /** Architecture type of the cluster */
  archType?: SpectroClusterMetaSummarySpecSummaryArchTypeItem[];
  cloudAccountUid?: string;
  cloudRegion?: string;
  cloudType?: string;
  clusterType?: string;
  importMode?: string;
  location?: ClusterMetaSpecLocation;
  projectMeta?: ProjectMeta;
  tags?: string[];
};
