/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Spectro cluster status
 */
export type SpectroClusterPairStatus = {
  /** Cluster Name associated to the pairing request */
  pairingClusterName?: string;
  /** Cluster UID associated to the pairing request */
  pairingClusterUid?: string;
  /** Spectro cluster status */
  state?: string;
};
