/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VariableFormat } from './variableFormat';

/**
 * Unique variable field with schema definition
 */
export type SpectroClusterVariableResponse = {
  /** The default value of the variable */
  defaultValue?: string;
  /** Variable description */
  description?: string;
  /** Unique display name of the variable */
  displayName?: string;
  format?: VariableFormat;
  /** If true, then variable will be hidden for overriding the value. By default the hidden flag will be set to false */
  hidden?: boolean;
  /** If true, then variable value can't be editable. By default the immutable flag will be set to false */
  immutable?: boolean;
  /** If true, then default value will be masked. By default the isSensitive flag will be set to false */
  isSensitive?: boolean;
  /** Variable name */
  name: string;
  /** Regular expression pattern which the variable value must match */
  regex?: string;
  /** Flag to specify if the variable is optional or mandatory. If it is mandatory then default value must be provided */
  required?: boolean;
  /** The user specified value of the variable */
  value?: string;
};
