/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Spectro application management cluster upgrade pack information
 */
export type SpectroMgmtUpgradePack = {
  /** Spectro application management cluster pack difference message */
  diffMessage?: string;
  /** Spectro application management cluster pack layer type */
  layer?: string;
  /** Spectro application management cluster pack name */
  name?: string;
  /** Spectro application management cluster pack registry unique identifier */
  registryUid?: string;
  /** Spectro application management cluster pack type */
  type?: string;
  /** Spectro application management cluster pack unique identifier */
  uid?: string;
  /** Spectro application management cluster pack values */
  values?: string;
  /** Spectro application management cluster pack version */
  version?: string;
};
