/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMetaInputEntity } from './objectMetaInputEntity';
import type { SpectroGenericClusterImportEntitySpec } from './spectroGenericClusterImportEntitySpec';

/**
 * Spectro generic cluster import request payload
 */
export type SpectroGenericClusterImportEntity = {
  metadata?: ObjectMetaInputEntity;
  spec?: SpectroGenericClusterImportEntitySpec;
};
