/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectReference } from './objectReference';
import type { ClusterConfig } from './clusterConfig';
import type { ClusterProfileTemplate } from './clusterProfileTemplate';
import type { SpectroClusterSpecClusterType } from './spectroClusterSpecClusterType';

/**
 * SpectroClusterSpec defines the desired state of SpectroCluster
 */
export type SpectroClusterSpec = {
  cloudConfigRef?: ObjectReference;
  cloudType?: string;
  clusterConfig?: ClusterConfig;
  /** When a cluster created from a clusterprofile at t1, ClusterProfileTemplate is a copy of the draft version or latest published version of the clusterprofileSpec.clusterprofileTemplate then clusterprofile may evolve to v2 at t2, but before user decide to upgrade the cluster, it will stay as it is when user decide to upgrade, clusterProfileTemplate will be updated from the clusterprofile pointed by ClusterProfileRef */
  clusterProfileTemplates?: ClusterProfileTemplate[];
  clusterType?: SpectroClusterSpecClusterType;
};
