/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { SpectroClusterRepaveSpec } from './spectroClusterRepaveSpec';
import type { SpectroClusterRepaveStatus } from './spectroClusterRepaveStatus';

/**
 * Spectro cluster repave status information
 */
export type SpectroClusterRepave = {
  metadata?: ObjectMeta;
  spec?: SpectroClusterRepaveSpec;
  status?: SpectroClusterRepaveStatus;
};
