/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { MaasClusterConfig } from './maasClusterConfig';
import type { MaasMachinePoolConfigEntity } from './maasMachinePoolConfigEntity';

/**
 * Maas cluster request payload for estimating rate
 */
export type SpectroMaasClusterRateEntity = {
  cloudConfig?: MaasClusterConfig;
  machinepoolconfig?: MaasMachinePoolConfigEntity[];
};
