/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SpectroClusterFilterSpec } from './spectroClusterFilterSpec';
import type { SpectroClusterSortSpec } from './spectroClusterSortSpec';

/**
 * Spectro cluster filter summary spec
 */
export type SpectroClusterSummarySpec = {
  filter?: SpectroClusterFilterSpec;
  sort?: SpectroClusterSortSpec[];
};
