/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EksClusterConfig } from './eksClusterConfig';
import type { EksMachinePoolConfigEntity } from './eksMachinePoolConfigEntity';

/**
 * Spectro EKS cluster request payload for estimating rate
 */
export type SpectroEksClusterRateEntity = {
  cloudConfig?: EksClusterConfig;
  machinepoolconfig?: EksMachinePoolConfigEntity[];
};
