/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AwsClusterConfig } from './awsClusterConfig';
import type { ClusterConfigEntity } from './clusterConfigEntity';
import type { ClusterType } from './clusterType';
import type { AwsMachinePoolConfigEntity } from './awsMachinePoolConfigEntity';
import type { SpectroClusterPolicies } from './spectroClusterPolicies';
import type { SpectroClusterProfileEntity } from './spectroClusterProfileEntity';

export type SpectroAwsClusterEntitySpec = {
  /** Cloud account uid to be used for cluster provisioning */
  cloudAccountUid: string;
  cloudConfig: AwsClusterConfig;
  clusterConfig?: ClusterConfigEntity;
  clusterType?: ClusterType;
  machinepoolconfig?: AwsMachinePoolConfigEntity[];
  policies?: SpectroClusterPolicies;
  profiles?: SpectroClusterProfileEntity[];
};
