/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SpectroMgmtUpgradeProfiles } from './spectroMgmtUpgradeProfiles';

/**
 * Spectro application management cluster upgrade profiles
 */
export type SpectroMgmtUpgradeSpc = {
  current?: SpectroMgmtUpgradeProfiles;
  target?: SpectroMgmtUpgradeProfiles;
};
