/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { AzureClusterConfig } from './azureClusterConfig';
import type { ClusterConfigEntity } from './clusterConfigEntity';
import type { AzureMachinePoolConfigEntity } from './azureMachinePoolConfigEntity';
import type { SpectroClusterPolicies } from './spectroClusterPolicies';
import type { SpectroClusterProfileEntity } from './spectroClusterProfileEntity';

export type SpectroAzureClusterEntitySpec = {
  /** Cloud account uid to be used for cluster provisioning */
  cloudAccountUid: string;
  cloudConfig: AzureClusterConfig;
  clusterConfig?: ClusterConfigEntity;
  machinepoolconfig?: AzureMachinePoolConfigEntity[];
  policies?: SpectroClusterPolicies;
  profiles?: SpectroClusterProfileEntity[];
};
