/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AzureClusterConfig } from './azureClusterConfig';
import type { AzureMachinePoolConfigEntity } from './azureMachinePoolConfigEntity';

/**
 * Spectro Azure cluster request payload for estimating rate
 */
export type SpectroAzureClusterRateEntity = {
  cloudConfig?: AzureClusterConfig;
  machinepoolconfig?: AzureMachinePoolConfigEntity[];
};
