/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterProfilePacksEntity } from './clusterProfilePacksEntity';
import type { ObjectReference } from './objectReference';

/**
 * Cluster profile spec response
 */
export type SpectroClusterProfileSpec = {
  /** Cluster profile cloud type */
  cloudType?: string;
  /** Cluster profile packs array */
  packs?: ClusterProfilePacksEntity[];
  relatedObject?: ObjectReference;
  /** Cluster profile type [ "cluster", "infra", "add-on", "system" ] */
  type?: string;
  /** Cluster profile version */
  version?: number;
};
