/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Spectro tenant cluster migration status
 */
export type SpectroTenantClusterMigration = {
  message?: string;
  name?: string;
  state?: string;
  uid?: string;
};
