/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { SpectroClusterUidSummarySpec } from './spectroClusterUidSummarySpec';
import type { SpectroClusterUidStatusSummary } from './spectroClusterUidStatusSummary';

/**
 * Spectro cluster summary
 */
export type SpectroClusterUidSummary = {
  metadata?: ObjectMeta;
  /** Spectro cluster spec summary */
  spec?: SpectroClusterUidSummarySpec;
  status?: SpectroClusterUidStatusSummary;
};
