/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { EksClusterConfig } from './eksClusterConfig';
import type { ClusterConfigEntity } from './clusterConfigEntity';
import type { ClusterTemplateRef } from './clusterTemplateRef';
import type { FargateProfile } from './fargateProfile';
import type { EksMachinePoolConfigEntity } from './eksMachinePoolConfigEntity';
import type { SpectroClusterPolicies } from './spectroClusterPolicies';
import type { SpectroClusterProfileEntity } from './spectroClusterProfileEntity';

export type SpectroEksClusterEntitySpec = {
  /** Cloud account uid to be used for cluster provisioning */
  cloudAccountUid: string;
  cloudConfig: EksClusterConfig;
  clusterConfig?: ClusterConfigEntity;
  clusterTemplate?: ClusterTemplateRef;
  fargateProfiles?: FargateProfile[];
  machinepoolconfig?: EksMachinePoolConfigEntity[];
  policies?: SpectroClusterPolicies;
  /** Cluster profile references that specify which profiles to apply to the cluster. Supports overriding pack values and variables. When template references are used, pack values cannot be overridden as they are retrieved from the template's pre-configured definitions. */
  profiles?: SpectroClusterProfileEntity[];
};
