/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SpectroClusterOidcIssuerTlsSpec } from './spectroClusterOidcIssuerTlsSpec';
import type { SpectroClusterOidcClaims } from './spectroClusterOidcClaims';

export type SpectroClusterOidcSpec = {
  clientId?: string;
  clientSecret?: string;
  issuerTls?: SpectroClusterOidcIssuerTlsSpec;
  /** the issuer is the URL identifier for the service */
  issuerUrl?: string;
  requiredClaims?: SpectroClusterOidcClaims;
  scopes?: string[];
};
