/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Variable with value which will be used within the packs of cluster profile
 */
export type SpectroClusterVariable = {
  /** Variable name */
  name: string;
  /** Actual value of the variable to be used within the cluster */
  value?: string;
};
