/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SpectroClusterHealthCondition } from './spectroClusterHealthCondition';
import type { Time } from './time';

/**
 * Spectro cluster health status
 */
export type SpectroClusterHealthStatus = {
  agentVersion?: string;
  conditions?: SpectroClusterHealthCondition[];
  lastHeartBeatTimestamp?: Time;
  state?: string;
};
