/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type SpectroClustersUidPackPropertiesParams = {
/**
 * Pack layer
 */
layer: string;
/**
 * Pack values yaml field path
 */
fieldPath: string;
/**
 * Pack name
 */
name?: string;
/**
 * Is the macros need to be resolved
 */
resolveMacros?: boolean;
};
