/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { SpectroInstallerEntitySpec } from './spectroInstallerEntitySpec';
import type { InstallerStatus } from './installerStatus';

/**
 * Spectro installer entity for create
 */
export type SpectroInstallerEntity = {
  metadata?: ObjectMeta;
  spec?: SpectroInstallerEntitySpec;
  status?: InstallerStatus;
};
