/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ArchType } from './archType';
import type { CloudConfigMeta } from './cloudConfigMeta';
import type { CloudAccountMeta } from './cloudAccountMeta';
import type { ClusterProfileTemplateMeta } from './clusterProfileTemplateMeta';

/**
 * Spectro cluster spec summary
 */
export type SpectroClusterUidSummarySpec = {
  /** Architecture types of the cluster */
  archTypes?: ArchType[];
  cloudConfig?: CloudConfigMeta;
  cloudaccount?: CloudAccountMeta;
  clusterProfileTemplate?: ClusterProfileTemplateMeta;
  clusterProfileTemplates?: ClusterProfileTemplateMeta[];
};
