/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { FilterString } from './filterString';

/**
 * Spectro cluster filter spec
 */
export type SpectroClusterMetadataFilterSpec = {
  environment?: string;
  includeVirtual?: boolean;
  /** isAlloy is renamed to isImported */
  isAlloy?: boolean;
  isImportReadOnly?: boolean;
  isImported?: boolean;
  name?: FilterString;
  state?: string;
};
