/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type SpectroClustersDeleteParams = {
/**
 * If set to true the cluster will be force deleted and user has to manually clean up the provisioned cloud resources
 */
forceDelete?: boolean;
};
