/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SshUserCredentials } from './sshUserCredentials';
import type { Time } from './time';
import type { SshUserStatusState } from './sshUserStatusState';

export type SshUserStatus = {
  credentials?: SshUserCredentials;
  lastModifiedTime?: Time;
  /** Message is the status message of the SSH tunnel */
  message?: string;
  /** State is the state of the SSH tunnel */
  state?: SshUserStatusState;
};
