/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { StoragePrice } from './storagePrice';

/**
 * Cloud storage cost
 */
export type StorageCost = {
  /** Cloud storage upper limit which is free. */
  discountedUsage?: string;
  /** Array of cloud storage range prices */
  price?: StoragePrice[];
};
