/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Cloud storage price within an upper limit.
 */
export type StoragePrice = {
  /** Upper limit of cloud storage usage */
  limit?: string;
  /** Price of cloud storage type */
  price?: string;
};
