/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Azure storage account provides a unique namespace for your Azure resources
 */
export type StorageAccount = {
  /** Fully qualified resource ID for the resource */
  id?: string;
  /** The kind of the resource */
  kind?: string;
  /** The geo-location where the resource lives */
  location?: string;
  /** The name of the resource */
  name?: string;
};
