/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type Subnet = {
  /** CidrBlock is the CIDR block to be used when the provider creates a managed Vnet. */
  cidrBlock?: string;
  name?: string;
  /** Resource group associated with a network security group */
  nsgResourceGroup?: string;
  /** Network Security Group(NSG) to be attached to subnet. NSG for a control plane subnet, should allow inbound to port 6443, as port 6443 is used by kubeadm to bootstrap the control planes */
  securityGroupName?: string;
};
