/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Azure Subscription Type
 */
export type Subscription = {
  /** The authorization source of the request. Valid values are one or more combinations of Legacy, RoleBased, Bypassed, Direct and Management */
  authorizationSource?: string;
  /** The subscription display name */
  displayName?: string;
  /** The subscription state. Possible values are Enabled, Warned, PastDue, Disabled, and Deleted. */
  state?: string;
  /** The subscription ID */
  subscriptionId?: string;
};
