/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SyftDependencyEntity } from './syftDependencyEntity';
import type { SyftImageContext } from './syftImageContext';
import type { Time } from './time';
import type { SyftVulnerabilityEntity } from './syftVulnerabilityEntity';
import type { SyftVulnerabilitySummaryEntity } from './syftVulnerabilitySummaryEntity';

/**
 * Syft report
 */
export type SyftReportEntity = {
  batchNo?: number;
  batchSize?: number;
  dependencies?: SyftDependencyEntity[];
  image?: string;
  imageContexts?: SyftImageContext[];
  sbom?: string;
  time?: Time;
  vulnerabilities?: SyftVulnerabilityEntity[];
  vulnerabilitySummary?: SyftVulnerabilitySummaryEntity;
};
