/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Compliance Scan Syft Context
 */
export type SyftScanContext = {
  format?: string;
  labelSelector?: string;
  namespace?: string;
  podName?: string;
  scope?: string;
};
