/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type SyftEntityStatus = typeof SyftEntityStatus[keyof typeof SyftEntityStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SyftEntityStatus = {
  Completed: 'Completed',
  InProgress: 'InProgress',
  Failed: 'Failed',
  Initiated: 'Initiated',
} as const;
