/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * system certificate in base64 format
 */
export type SystemCertificatesSpec = {
  caCertificateBase64?: string;
  certificateBase64?: string;
  insecureSkipVerify?: boolean;
  keyBase64?: string;
};
