/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { SystemPlanCredit } from './systemPlanCredit';
import type { SystemPlanLimit } from './systemPlanLimit';
import type { Time } from './time';

/**
 * system plan
 */
export type SystemPlan = {
  freeCredits?: SystemPlanCredit[];
  planLimit?: SystemPlanLimit;
  slaCredits?: SystemPlanCredit[];
  systemStartDate?: Time;
};
