/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * User specifications
 */
export type SystemUserSpec = {
  /** Admin type */
  adminType?: string;
  /** System User's email id */
  emailId?: string;
};
