/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * System AWS Gov account specifications
 */
export type SystemAwsStsAccount = {
  accessKey?: string;
  accountId?: string;
  secretKey?: string;
};
