/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * SystemsManager specifies the Systems Manager configuration for the AWS/EKS cluster
 */
export type SystemsManager = {
  /** ActivationCode specifies the Systems Manager activation code */
  activationCode?: string;
  /** ActivationID specifies the Systems Manager activation ID */
  activationId?: string;
};
