/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type SystemPlanCreditType = typeof SystemPlanCreditType[keyof typeof SystemPlanCreditType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SystemPlanCreditType = {
  Pure: 'Pure',
  Alloy: 'Alloy',
} as const;
