/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type SystemActivationResponseStatusState = typeof SystemActivationResponseStatusState[keyof typeof SystemActivationResponseStatusState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SystemActivationResponseStatusState = {
  Pending: 'Pending',
  Active: 'Active',
  Inactive: 'Inactive',
} as const;
