/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type SystemSysplanSpecType = typeof SystemSysplanSpecType[keyof typeof SystemSysplanSpecType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SystemSysplanSpecType = {
  Trial: 'Trial',
  Unlimited: 'Unlimited',
} as const;
