/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SystemReverseProxyProtocol } from './systemReverseProxyProtocol';

/**
 * system config reverse proxy
 */
export type SystemReverseProxy = {
  caCert?: string;
  clientCert?: string;
  clientKey?: string;
  port?: number;
  protocol?: SystemReverseProxyProtocol;
  server?: string;
  vHostPort?: number;
};
