/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * system sso github config spec
 */
export type SystemGithubSsoSpec = {
  clientId?: string;
  clientSecretKey?: string;
  isEnabled?: boolean;
  logoUrl?: string;
};
