/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type SystemFeaturesSpec = {
  /** Feature description */
  description?: string;
  /** Feature doc link */
  docLink?: string;
  /** Flag which specifies if feature is allowed or not */
  isAllowed?: boolean;
  /** Unique Feature key */
  key?: string;
};
