/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { SystemSsoAuthSpec } from './systemSsoAuthSpec';

/**
 * system sso config spec
 */
export type SystemSsoSpec = {
  acsUrlRoot?: string;
  acsUrlScheme?: string;
  apiVersion?: string;
  audienceUrl?: string;
  authSpec?: SystemSsoAuthSpec;
  entityId?: string;
};
