/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { PlanLimit } from './planLimit';
import type { InvoiceBillingPeriod } from './invoiceBillingPeriod';
import type { YearlyUsage } from './yearlyUsage';

/**
 * System usage billing object
 */
export type SystemUsage = {
  planLimit?: PlanLimit;
  usageBillingPeriod?: InvoiceBillingPeriod;
  /** List of every year system usage */
  yearlyUsages?: YearlyUsage[];
};
