/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * system web kubectl config spec
 */
export type SystemOciImageRegistry = {
  baseContentPath?: string;
  caCert?: string;
  endpoint?: string;
  insecureSkipVerify?: boolean;
  mirrorRegistries?: string;
  name?: string;
  password?: string;
  username?: string;
};
