/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { TaintEffect } from './taintEffect';
import type { Time } from './time';

/**
 * Taint
 */
export type Taint = {
  effect?: TaintEffect;
  /** The taint key to be applied to a node */
  key?: string;
  timeAdded?: Time;
  /** The taint value corresponding to the taint key. */
  value?: string;
};
