/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * @nullable
 */
export type TeamSummarySortFields = typeof TeamSummarySortFields[keyof typeof TeamSummarySortFields] | null;


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TeamSummarySortFields = {
  name: 'name',
  creationTimestamp: 'creationTimestamp',
} as const;
