/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Address } from './address';

/**
 * Tenant Spec
 */
export type TenantSpec = {
  address?: Address;
  authType?: string;
  defaultLoginMode?: string;
  orgEmailId?: string;
  orgName?: string;
  planUid?: string;
};
