/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { TenantClusterRbacSettingsAutomaticClusterRoleBinding } from './tenantClusterRbacSettingsAutomaticClusterRoleBinding';

/**
 * Tenant cluster RBAC settings
 */
export type TenantClusterRbacSettings = {
  /** Specifies the mode for automatic creation and management of cluster role bindings for tenant clusters */
  automaticClusterRoleBinding?: TenantClusterRbacSettingsAutomaticClusterRoleBinding;
};
