/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Tenant usage object
 */
export type TenantUsage = {
  /** Organization name */
  orgName?: string;
  /** Tenant uid */
  tenantUid?: string;
  /** Credits used by imported clusters */
  usedAlloyCredits?: number;
  /** Credits used by managed clusters */
  usedPureCredits?: number;
};
