/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Specifies the mode for automatic creation and management of cluster role bindings for tenant clusters
 */
export type TenantClusterRbacSettingsAutomaticClusterRoleBinding = typeof TenantClusterRbacSettingsAutomaticClusterRoleBinding[keyof typeof TenantClusterRbacSettingsAutomaticClusterRoleBinding];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TenantClusterRbacSettingsAutomaticClusterRoleBinding = {
  none: 'none',
  enabled: 'enabled',
  disabled: 'disabled',
} as const;
