/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

/**
 * Tenant contract settings
 */
export type TenantContractSpec = {
  acceptedTime?: Time;
  /** If the contract is accepted offline, then set this field to true */
  isAccepted: boolean;
  /** Is the contract required, for on-prem installation it will be false */
  isRequired: boolean;
};
