/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ObjectMeta } from './objectMeta';
import type { ThemeSpec } from './themeSpec';
import type { ThemeStatus } from './themeStatus';

/**
 * Theme data entity
 */
export type Theme = {
  metadata?: ObjectMeta;
  spec?: ThemeSpec;
  status?: ThemeStatus;
};
