/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

/**
 * transfer job details
 */
export type TransferJob = {
  finishTime?: Time;
  folder?: string;
  isCompleted?: boolean;
  message?: string[];
  startTime?: Time;
  state?: string;
  status?: string[];
};
