/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Update strategy type. Defaults to RollingUpdateScaleOut if empty.
 */
export type UpdateStrategyType = typeof UpdateStrategyType[keyof typeof UpdateStrategyType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateStrategyType = {
  RollingUpdateScaleOut: 'RollingUpdateScaleOut',
  RollingUpdateScaleIn: 'RollingUpdateScaleIn',
  OverrideScaling: 'OverrideScaling',
} as const;
