/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { S3StorageConfig } from './s3StorageConfig';

/**
 * S3 location specification
 */
export type UserAssetsLocationS3Spec = {
  config: S3StorageConfig;
  /** Set to 'true', if location has to be set as default */
  isDefault?: boolean;
  /** S3 location type [s3/minio] */
  type?: string;
};
