/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { UserMeStatusProjectPermissions } from './userMeStatusProjectPermissions';
import type { UserMeTenant } from './userMeTenant';
import type { UserMeStatusTenantPermissions } from './userMeStatusTenantPermissions';

/**
 * User status with permissions
 */
export type UserMeStatus = {
  /** Contains activation link for the user */
  activationLink?: string;
  /** Specifies if user account is active/disabled */
  isActive?: boolean;
  /** Specifies if user account has accepted the contract */
  isContractAccepted?: boolean;
  /** User's login Mode */
  loginMode?: string;
  projectPermissions?: UserMeStatusProjectPermissions;
  tenant?: UserMeTenant;
  tenantPermissions?: UserMeStatusTenantPermissions;
};
