/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { UsersFilterSpec } from './usersFilterSpec';
import type { UserSummarySortSpec } from './userSummarySortSpec';

/**
 * Users filter summary spec
 */
export type UsersSummarySpec = {
  filter?: UsersFilterSpec;
  sort?: UserSummarySortSpec[];
};
