/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { UserSummary } from './userSummary';
import type { ListMetaData } from './listMetaData';

/**
 * Deprecated, Use v1UsersSummaryList - Returns User summary
 */
export type UsersSummary = {
  items: UserSummary[];
  listmeta?: ListMetaData;
};
