/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

/**
 * User status
 */
export type UserStatus = {
  /** provides the link to activate or reset the user password */
  activationLink?: string;
  /** Specifies if user account is active/disabled */
  isActive?: boolean;
  /** Specifies if user in multi org requested password reset */
  isPasswordResetting?: boolean;
  lastSignIn?: Time;
};
