/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { GcpStorageConfig } from './gcpStorageConfig';

/**
 * GCP location specification
 */
export type UserAssetsLocationGcpSpec = {
  config: GcpStorageConfig;
  /** Set to 'true', if location has to be set as default */
  isDefault?: boolean;
  /** GCP location type [gcp] */
  type?: string;
};
