/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * User Profile specifications
 */
export type UserProfileSpec = {
  /** User's email id */
  emailId?: string;
  firstName?: string;
  lastName?: string;
};
