/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { V1AwsAccountStsGetPartition } from './v1AwsAccountStsGetPartition';

export type V1AwsAccountStsGetParams = {
/**
 * AWS accounts are scoped to a single partition. Allowed values [aws, aws-us-gov], Default values
 */
partition?: V1AwsAccountStsGetPartition;
};
