/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type V1AwsSecurityGroupsParams = {
/**
 * Uid for the specific AWS cloud account
 */
cloudAccountUid?: string;
/**
 * Region for which security groups are requested
 */
region: string;
/**
 * Vpc Id for which security groups are requested
 */
vpcId: string;
};
