/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type V1AwsInstanceTypesParams = {
/**
 * Filter for instances having cpu greater than or equal
 */
cpuGtEq?: number;
/**
 * Filter for instances having memory greater than or equal
 */
memoryGtEq?: number;
/**
 * Filter for instances having gpu greater than or equal
 */
gpuGtEq?: number;
/**
 * Uid for the specific AWS cloud account
 */
cloudAccountUid?: string;
/**
 * Optional HRG ARN to filter instance types by HRG supported families
 * @pattern ^arn:aws[a-z\-]*:resource-groups:[a-z0-9\-]+:[0-9]{12}:group/[a-zA-Z0-9\-_]+$
 */
hrgArn?: string;
};
