/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type V1AwsInstanceTypesParams = {
/**
 * Filter for instances having cpu greater than or equal
 */
cpuGtEq?: number;
/**
 * Filter for instances having memory greater than or equal
 */
memoryGtEq?: number;
/**
 * Filter for instances having gpu greater than or equal
 */
gpuGtEq?: number;
/**
 * Uid for the specific AWS cloud account
 */
cloudAccountUid?: string;
};
