/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Contains configuration for Azure cloud
 */
export type V1AzureAccountEntitySpecClientCloud = typeof V1AzureAccountEntitySpecClientCloud[keyof typeof V1AzureAccountEntitySpecClientCloud];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const V1AzureAccountEntitySpecClientCloud = {
  'azure-china': 'azure-china',
  'azure-government': 'azure-government',
  public: 'public',
} as const;
