/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type V1AzureStorageAccountTypesParams = {
/**
 * Region for which Azure storage account types are requested
 */
region?: string;
};
