/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { V1ClusterProfilesUidExportFormat } from './v1ClusterProfilesUidExportFormat';

export type V1ClusterProfilesUidExportParams = {
/**
 * Cluster profile export file format [ "yaml", "json" ]
 */
format?: V1ClusterProfilesUidExportFormat;
};
