/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type V1CloudStackNetworksGetParams = {
/**
 * Uid for the specific CloudStack cloud account
 */
cloudAccountUid?: string;
/**
 * Zone for which CloudStack networks are requested
 */
zone?: string;
/**
 * Project ID for which CloudStack networks are requested
 */
projectId?: string;
/**
 * VPC ID for which CloudStack networks are requested
 */
vpcId?: string;
};
