/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type V1ClusterProfilesUidExportFormat = typeof V1ClusterProfilesUidExportFormat[keyof typeof V1ClusterProfilesUidExportFormat];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const V1ClusterProfilesUidExportFormat = {
  yaml: 'yaml',
  json: 'json',
} as const;
