/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { AwsCloudAccount } from './awsCloudAccount';

/**
 * Cloud watch config entity
 */
export type V1CloudWatchConfig = {
  credentials?: AwsCloudAccount;
  /** Name of the group */
  group?: string;
  /** Name of the region */
  region?: string;
  /** Name of the stream */
  stream?: string;
};
