/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { V1DataSinkPayload } from './v1DataSinkPayload';

/**
 * List of data sink payload entities
 */
export type V1DataSinkPayloads = V1DataSinkPayload[];
