/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type V1GcpContainerImageValidateParams = {
/**
 * image path in the container
 */
imagePath: string;
/**
 * tag in the GCP container
 */
tag: string;
};
