/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type V1OpenStackKeypairsGetParams = {
/**
 * Uid for the specific OpenStack cloud account
 */
cloudAccountUid?: string;
/**
 * project for which OpenStack keypairs are requested
 */
project?: string;
/**
 * region for which OpenStack keypairs are requested
 */
region?: string;
/**
 * domain for which OpenStack keypairs are requested
 */
domain?: string;
};
