/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type V1SamlCallbackBody = {
  /** Describe the SAML compliant response sent by IDP which will be validated by Palette */
  SAMLResponse?: string;
  /** Describes a state to validate and associate request and response */
  RelayState?: string;
};
