/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { APIEndpoint } from './aPIEndpoint';
import type { VirtualClusterHelmRelease } from './virtualClusterHelmRelease';

/**
 * Cluster level configuration for virtual cluster
 */
export type VirtualClusterConfig = {
  controlPlaneEndpoint?: APIEndpoint;
  helmRelease?: VirtualClusterHelmRelease;
  kubernetesVersion?: string;
};
