/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { Subnet } from './subnet';

/**
 * Azure virtual network is the fundamental building block for your private network in Azure.
 */
export type VirtualNetwork = {
  /** Location of the virtual network */
  addressSpaces?: string[];
  /** The ID of the resource group */
  id?: string;
  /** Location of the virtual network */
  location?: string;
  /** Name of the virtual network */
  name?: string;
  /** List of subnets associated with Azure VPC */
  subnets?: Subnet[];
  /** Type of the virtual network */
  type?: string;
};
