/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ObjectResReference } from './objectResReference';
import type { LifecycleStatus } from './lifecycleStatus';

export type Virtual = {
  /** list of apps deployed on the virtual cluster */
  appDeployments?: ObjectResReference[];
  clusterGroup?: ObjectResReference;
  hostCluster?: ObjectResReference;
  lifecycleStatus?: LifecycleStatus;
  /** cluster virtual host status */
  state?: string;
  /** list of virtual clusters deployed on the cluster */
  virtualClusters?: ObjectResReference[];
};
