/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmCondition } from './vmCondition';
import type { Time } from './time';
import type { VmError } from './vmError';
import type { VmSnapshotVolumesLists } from './vmSnapshotVolumesLists';

/**
 * VirtualMachineSnapshotStatus is the status for a VirtualMachineSnapshot resource
 * @nullable
 */
export type VirtualMachineSnapshotStatus = {
  conditions?: VmCondition[];
  creationTime?: Time;
  error?: VmError;
  indications?: string[];
  phase?: string;
  readyToUse?: boolean;
  snapshotVolumes?: VmSnapshotVolumesLists;
  sourceUID?: string;
  virtualMachineSnapshotContentName?: string;
} | null;
