/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type VmAccessCredentialSecretSource = {
  /** SecretName represents the name of the secret in the VMI's namespace */
  secretName: string;
};
