/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * If set (default), BIOS will be used.
 */
export type VmBIOS = {
  /** If set, the BIOS output will be transmitted over serial */
  useSerial?: boolean;
};
