/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmCustomBlockSize } from './vmCustomBlockSize';
import type { VmFeatureState } from './vmFeatureState';

/**
 * BlockSize provides the option to change the block size presented to the VM for a disk. Only one of its members may be specified.
 */
export type VmBlockSize = {
  custom?: VmCustomBlockSize;
  matchVolume?: VmFeatureState;
};
