/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmBIOS } from './vmBIOS';
import type { VmEFI } from './vmEFI';

/**
 * Represents the firmware blob used to assist in the domain creation process. Used for setting the QEMU BIOS file path for the libvirt domain.
 */
export type VmBootloader = {
  bios?: VmBIOS;
  efi?: VmEFI;
};
