/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Chassis specifies the chassis info passed to the domain.
 */
export type VmChassis = {
  asset?: string;
  manufacturer?: string;
  serial?: string;
  sku?: string;
  version?: string;
};
