/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmTimer } from './vmTimer';
import type { VmClockOffsetUTC } from './vmClockOffsetUTC';

/**
 * Represents the clock and timers of a vmi.
 */
export type VmClock = {
  timer?: VmTimer;
  /** Timezone sets the guest clock to the specified timezone. Zone name follows the TZ environment variable format (e.g. 'America/New_York'). */
  timezone?: string;
  utc?: VmClockOffsetUTC;
};
