/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * DataVolumeSourcePVC provides the parameters to create a Data Volume from an existing PVC
 */
export type VmDataVolumeSourcePVC = {
  /** The name of the source PVC */
  name: string;
  /** The namespace of the source PVC */
  namespace: string;
};
