/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmDataVolumeBlankImage } from './vmDataVolumeBlankImage';
import type { VmDataVolumeSourceGCS } from './vmDataVolumeSourceGCS';
import type { VmDataVolumeSourceHttp } from './vmDataVolumeSourceHttp';
import type { VmDataVolumeSourceImageIO } from './vmDataVolumeSourceImageIO';
import type { VmDataVolumeSourcePVC } from './vmDataVolumeSourcePVC';
import type { VmDataVolumeSourceRegistry } from './vmDataVolumeSourceRegistry';
import type { VmDataVolumeSourceS3 } from './vmDataVolumeSourceS3';
import type { VmDataVolumeSourceSnapshot } from './vmDataVolumeSourceSnapshot';
import type { VmDataVolumeSourceUpload } from './vmDataVolumeSourceUpload';
import type { VmDataVolumeSourceVDDK } from './vmDataVolumeSourceVDDK';

/**
 * DataVolumeSource represents the source for our Data Volume, this can be HTTP, Imageio, S3, GCS, Registry, Snapshot or an existing PVC
 */
export type VmDataVolumeSource = {
  blank?: VmDataVolumeBlankImage;
  gcs?: VmDataVolumeSourceGCS;
  http?: VmDataVolumeSourceHttp;
  imageio?: VmDataVolumeSourceImageIO;
  pvc?: VmDataVolumeSourcePVC;
  registry?: VmDataVolumeSourceRegistry;
  s3?: VmDataVolumeSourceS3;
  snapshot?: VmDataVolumeSourceSnapshot;
  upload?: VmDataVolumeSourceUpload;
  vddk?: VmDataVolumeSourceVDDK;
};
