/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmObjectMeta } from './vmObjectMeta';
import type { VmDataVolumeSpec } from './vmDataVolumeSpec';

export type VmDataVolumeTemplateSpec = {
  /** APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. */
  apiVersion?: string;
  /** Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. */
  kind?: string;
  metadata?: VmObjectMeta;
  spec: VmDataVolumeSpec;
};
