/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * DataVolumeSourceRef defines an indirect reference to the source of data for the DataVolume
 */
export type VmDataVolumeSourceRef = {
  /** The kind of the source reference, currently only "DataSource" is supported */
  kind: string;
  /** The name of the source reference */
  name: string;
  /** The namespace of the source reference, defaults to the DataVolume namespace */
  namespace?: string;
};
