/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * DataVolumeBlankImage provides the parameters to create a new raw blank image for the PVC
 */
export type VmDataVolumeBlankImage = { [key: string]: unknown };
