/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * DataVolumeSourceSnapshot provides the parameters to create a Data Volume from an existing VolumeSnapshot
 */
export type VmDataVolumeSourceSnapshot = {
  /** The name of the source VolumeSnapshot */
  name: string;
  /** The namespace of the source VolumeSnapshot */
  namespace: string;
};
