/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmDataVolumeCheckpoint } from './vmDataVolumeCheckpoint';
import type { VmPersistentVolumeClaimSpec } from './vmPersistentVolumeClaimSpec';
import type { VmDataVolumeSource } from './vmDataVolumeSource';
import type { VmDataVolumeSourceRef } from './vmDataVolumeSourceRef';
import type { VmStorageSpec } from './vmStorageSpec';

/**
 * DataVolumeSpec defines the DataVolume type specification
 */
export type VmDataVolumeSpec = {
  /** Checkpoints is a list of DataVolumeCheckpoints, representing stages in a multistage import. */
  checkpoints?: VmDataVolumeCheckpoint[];
  /** DataVolumeContentType options: "kubevirt", "archive" */
  contentType?: string;
  /** FinalCheckpoint indicates whether the current DataVolumeCheckpoint is the final checkpoint. */
  finalCheckpoint?: boolean;
  /** Preallocation controls whether storage for DataVolumes should be allocated in advance. */
  preallocation?: boolean;
  /** PriorityClassName for Importer, Cloner and Uploader pod */
  priorityClassName?: string;
  pvc?: VmPersistentVolumeClaimSpec;
  source?: VmDataVolumeSource;
  sourceRef?: VmDataVolumeSourceRef;
  storage?: VmStorageSpec;
};
