/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmClientPassthroughDevices } from './vmClientPassthroughDevices';
import type { VmDisk } from './vmDisk';
import type { VmFilesystem } from './vmFilesystem';
import type { VmGPU } from './vmGPU';
import type { VmHostDevice } from './vmHostDevice';
import type { VmInput } from './vmInput';
import type { VmInterface } from './vmInterface';
import type { VmRng } from './vmRng';
import type { VmSoundDevice } from './vmSoundDevice';
import type { VmTPMDevice } from './vmTPMDevice';
import type { VmWatchdog } from './vmWatchdog';

export type VmDevices = {
  /** Whether to attach the default graphics device or not. VNC will not be available if set to false. Defaults to true. */
  autoattachGraphicsDevice?: boolean;
  /** Whether to attach an Input Device. Defaults to false. */
  autoattachInputDevice?: boolean;
  /** Whether to attach the Memory balloon device with default period. Period can be adjusted in virt-config. Defaults to true. */
  autoattachMemBalloon?: boolean;
  /** Whether to attach a pod network interface. Defaults to true. */
  autoattachPodInterface?: boolean;
  /** Whether to attach the default serial console or not. Serial console access will not be available if set to false. Defaults to true. */
  autoattachSerialConsole?: boolean;
  /** Whether to attach the VSOCK CID to the VM or not. VSOCK access will be available if set to true. Defaults to false. */
  autoattachVSOCK?: boolean;
  /** Whether or not to enable virtio multi-queue for block devices. Defaults to false. */
  blockMultiQueue?: boolean;
  clientPassthrough?: VmClientPassthroughDevices;
  /** DisableHotplug disabled the ability to hotplug disks. */
  disableHotplug?: boolean;
  /** Disks describes disks, cdroms and luns which are connected to the vmi. */
  disks?: VmDisk[];
  /** Filesystems describes filesystem which is connected to the vmi. */
  filesystems?: VmFilesystem[];
  /** Whether to attach a GPU device to the vmi. */
  gpus?: VmGPU[];
  /** Whether to attach a host device to the vmi. */
  hostDevices?: VmHostDevice[];
  /** Inputs describe input devices */
  inputs?: VmInput[];
  /** Interfaces describe network interfaces which are added to the vmi. */
  interfaces?: VmInterface[];
  /** If specified, virtual network interfaces configured with a virtio bus will also enable the vhost multiqueue feature for network devices. The number of queues created depends on additional factors of the VirtualMachineInstance, like the number of guest CPUs. */
  networkInterfaceMultiqueue?: boolean;
  rng?: VmRng;
  sound?: VmSoundDevice;
  tpm?: VmTPMDevice;
  /** Fall back to legacy virtio 0.9 support if virtio bus is selected on devices. This is helpful for old machines like CentOS6 or RHEL6 which do not understand virtio_non_transitional (virtio 1.0). */
  useVirtioTransitional?: boolean;
  watchdog?: VmWatchdog;
};
