/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmDHCPPrivateOptions } from './vmDHCPPrivateOptions';

/**
 * Extra DHCP options to use in the interface.
 */
export type VmDHCPOptions = {
  /** If specified will pass option 67 to interface's DHCP server */
  bootFileName?: string;
  /** If specified will pass the configured NTP server to the VM via DHCP option 042. */
  ntpServers?: string[];
  /** If specified will pass extra DHCP options for private use, range: 224-254 */
  privateOptions?: VmDHCPPrivateOptions[];
  /** If specified will pass option 66 to interface's DHCP server */
  tftpServerName?: string;
};
