/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type VmDiskTarget = {
  /** Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi, usb. */
  bus?: string;
  /** If specified, the virtual disk will be placed on the guests pci address with the specified PCI address. For example: 0000:81:01.10 */
  pciAddress?: string;
  /** ReadOnly. Defaults to false. */
  readonly?: boolean;
};
