/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmBlockSize } from './vmBlockSize';
import type { VmCDRomTarget } from './vmCDRomTarget';
import type { VmDiskTarget } from './vmDiskTarget';
import type { VmLunTarget } from './vmLunTarget';

export type VmDisk = {
  blockSize?: VmBlockSize;
  /** BootOrder is an integer value > 0, used to determine ordering of boot devices. Lower values take precedence. Each disk or interface that has a boot order must have a unique value. Disks without a boot order are not tried if a disk with a boot order exists. */
  bootOrder?: number;
  /** Cache specifies which kvm disk cache mode should be used. Supported values are: CacheNone, CacheWriteThrough. */
  cache?: string;
  cdrom?: VmCDRomTarget;
  /** dedicatedIOThread indicates this disk should have an exclusive IO Thread. Enabling this implies useIOThreads = true. Defaults to false. */
  dedicatedIOThread?: boolean;
  disk?: VmDiskTarget;
  /** IO specifies which QEMU disk IO mode should be used. Supported values are: native, default, threads. */
  io?: string;
  lun?: VmLunTarget;
  /** Name is the device name */
  name: string;
  /** Serial provides the ability to specify a serial number for the disk device. */
  serial?: string;
  /** If specified the disk is made sharable and multiple write from different VMs are permitted */
  shareable?: boolean;
  /** If specified, disk address and its tag will be provided to the guest via config drive metadata */
  tag?: string;
};
