/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * IOThreads specifies the IOThreads options.
 */
export type VmDomainSpecIoThreads = {
  /** SupplementalPoolThreadCount specifies how many iothreads are allocated for the supplementalPool policy. */
  supplementalPoolThreadCount?: number;
};
