/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmChassis } from './vmChassis';
import type { VmClock } from './vmClock';
import type { VmCpu } from './vmCpu';
import type { VmDevices } from './vmDevices';
import type { VmFeatures } from './vmFeatures';
import type { VmFirmware } from './vmFirmware';
import type { VmLaunchSecurity } from './vmLaunchSecurity';
import type { VmMachine } from './vmMachine';
import type { VmMemory } from './vmMemory';
import type { VmResourceRequirements } from './vmResourceRequirements';

export type VmDomainSpec = {
  chassis?: VmChassis;
  clock?: VmClock;
  cpu?: VmCpu;
  devices: VmDevices;
  features?: VmFeatures;
  firmware?: VmFirmware;
  /** Controls whether or not disks will share IOThreads. Omitting IOThreadsPolicy disables use of IOThreads. One of: shared, auto */
  ioThreadsPolicy?: string;
  launchSecurity?: VmLaunchSecurity;
  machine?: VmMachine;
  memory?: VmMemory;
  resources?: VmResourceRequirements;
};
