/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmFeatureState } from './vmFeatureState';
import type { VmFeatureSpinlocks } from './vmFeatureSpinlocks';
import type { VmSyNICTimer } from './vmSyNICTimer';
import type { VmFeatureVendorId } from './vmFeatureVendorId';

/**
 * Hyperv specific features.
 */
export type VmFeatureHyperv = {
  evmcs?: VmFeatureState;
  frequencies?: VmFeatureState;
  ipi?: VmFeatureState;
  reenlightenment?: VmFeatureState;
  relaxed?: VmFeatureState;
  reset?: VmFeatureState;
  runtime?: VmFeatureState;
  spinlocks?: VmFeatureSpinlocks;
  synic?: VmFeatureState;
  synictimer?: VmSyNICTimer;
  tlbflush?: VmFeatureState;
  vapic?: VmFeatureState;
  vendorid?: VmFeatureVendorId;
  vpindex?: VmFeatureState;
};
