/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Hugepages allow to use hugepages for the VirtualMachineInstance instead of regular memory.
 */
export type VmHugepages = {
  /** PageSize specifies the hugepage size, for x86_64 architecture valid values are 1Gi and 2Mi. */
  pageSize?: string;
};
