/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * HyperVPassthrough enables all supported hyperv flags automatically. Bear in mind that if this enabled hyperV features cannot be enabled explicitly. In addition, a Virtual Machine using it will be non-migratable.
 */
export type VmHyperVPassthrough = {
  /** Enabled determines if Hyper-V passthrough should be enabled or disabled. Defaults to false. */
  enabled?: boolean;
};
