/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * i6300esb watchdog device.
 */
export type VmI6300ESBWatchdog = {
  /** The action to take. Valid values are poweroff, reset, shutdown. Defaults to reset. */
  action?: string;
};
