/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * InterfaceMacvtap connects to a given network by extending the Kubernetes node's L2 networks via a macvtap interface.
 */
export type VmInterfaceMacvtap = { [key: string]: unknown };
