/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * If set, the VM will be booted from the defined kernel / initrd.
 */
export type VmKernelBootContainer = {
  /** Image that contains initrd / kernel files. */
  image: string;
  /** Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: https://kubernetes.io/docs/concepts/containers/images#updating-images */
  imagePullPolicy?: string;
  /** ImagePullSecret is the name of the Docker registry secret required to pull the image. The secret must already exist. */
  imagePullSecret?: string;
  /** the fully-qualified path to the ramdisk image in the host OS */
  initrdPath?: string;
  /** The fully-qualified path to the kernel image in the host OS */
  kernelPath?: string;
};
