/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type VmLunTarget = {
  /** Bus indicates the type of disk device to emulate. supported values: virtio, sata, scsi. */
  bus?: string;
  /** ReadOnly. Defaults to false. */
  readonly?: boolean;
};
