/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Represents the multus cni network.
 */
export type VmMultusNetwork = {
  /** Select the default network and add it to the multus-cni.io/default-network annotation. */
  default?: boolean;
  /** References to a NetworkAttachmentDefinition CRD object. Format: <networkName>, <namespace>/<networkName>. If namespace is not specified, VMI namespace is assumed. */
  networkName: string;
};
