/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmNodeSelectorTerm } from './vmNodeSelectorTerm';

/**
 * A node selector represents the union of the results of one or more label queries over a set of nodes; that is, it represents the OR of the selectors represented by the node selector terms.
 */
export type VmNodeSelector = {
  /** Required. A list of node selector terms. The terms are ORed. */
  nodeSelectorTerms: VmNodeSelectorTerm[];
};
