/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmTypedLocalObjectReference } from './vmTypedLocalObjectReference';
import type { VmCoreResourceRequirements } from './vmCoreResourceRequirements';
import type { VmLabelSelector } from './vmLabelSelector';

/**
 * PersistentVolumeClaimSpec describes the common attributes of storage devices and allows a Source for provider-specific attributes
 */
export type VmPersistentVolumeClaimSpec = {
  /** AccessModes contains the desired access modes the volume should have. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#access-modes-1 */
  accessModes?: string[];
  dataSource?: VmTypedLocalObjectReference;
  dataSourceRef?: VmTypedLocalObjectReference;
  resources?: VmCoreResourceRequirements;
  selector?: VmLabelSelector;
  /** Name of the StorageClass required by the claim. More info: https://kubernetes.io/docs/concepts/storage/persistent-volumes#class-1 */
  storageClassName?: string;
  /** volumeMode defines what type of volume is required by the claim. Value of Filesystem is implied when not included in claim spec. */
  volumeMode?: string;
  /** VolumeName is the binding reference to the PersistentVolume backing this claim. */
  volumeName?: string;
};
