/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

/**
 * Port represents a port to expose from the virtual machine. Default protocol TCP. The port field is mandatory
 */
export type VmPort = {
  /** If specified, this must be an IANA_SVC_NAME and unique within the pod. Each named port in a pod must have a unique name. Name for the port that can be referred to by services. */
  name?: string;
  /** Number of port to expose for the virtual machine. This must be a valid port number, 0 < x < 65536. */
  port: number;
  /** Protocol for port. Must be UDP or TCP. Defaults to "TCP". */
  protocol?: string;
};
