/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * PodDNSConfigOption defines DNS resolver options of a pod.
 */
export type VmPodDnsConfigOption = {
  /** Required. */
  name?: string;
  value?: string;
};
