/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

export type VmQemuGuestAgentSshPublicKeyAccessCredentialPropagation = {
  /** Users represents a list of guest users that should have the ssh public keys added to their authorized_keys file. */
  users: string[];
};
