/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmQuantity } from './vmQuantity';

/**
 * ResourceFieldSelector represents container resources (cpu, memory) and their output format
 */
export type VmResourceFieldSelector = {
  /** Container name: required for volumes, optional for env vars */
  containerName?: string;
  divisor?: VmQuantity;
  /** Required: resource to select */
  resource: string;
};
