/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmRemoveVolumeOptions } from './vmRemoveVolumeOptions';

export type VMRemoveVolumeEntity = {
  /** If 'true' remove the disk from the Virtual Machine & Virtual Machine Instance, else remove the disk from the Virtual Machine Instance only */
  persist?: boolean;
  removeVolumeOptions: VmRemoveVolumeOptions;
};
