/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */

/**
 * Represents the user's configuration to emulate sound cards in the VMI.
 */
export type VmSoundDevice = {
  /** We only support ich9 or ac97. If SoundDevice is not set: No sound card is emulated. If SoundDevice is set but Model is not: ich9 */
  model?: string;
  /** User's defined name for this sound device */
  name: string;
};
