/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmConfigDriveSshPublicKeyAccessCredentialPropagation } from './vmConfigDriveSshPublicKeyAccessCredentialPropagation';
import type { VmQemuGuestAgentSshPublicKeyAccessCredentialPropagation } from './vmQemuGuestAgentSshPublicKeyAccessCredentialPropagation';

/**
 * SSHPublicKeyAccessCredentialPropagationMethod represents the method used to inject a ssh public key into the vm guest. Only one of its members may be specified.
 */
export type VmSshPublicKeyAccessCredentialPropagationMethod = {
  configDrive?: VmConfigDriveSshPublicKeyAccessCredentialPropagation;
  qemuGuestAgent?: VmQemuGuestAgentSshPublicKeyAccessCredentialPropagation;
};
