/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { Time } from './time';

/**
 * VirtualMachineMemoryDumpRequest represent the memory dump request phase and info
 */
export type VmVirtualMachineMemoryDumpRequest = {
  /** ClaimName is the name of the pvc that will contain the memory dump */
  claimName: string;
  endTimestamp?: Time;
  /** FileName represents the name of the output file */
  fileName?: string;
  /** Message is a detailed message about failure of the memory dump */
  message?: string;
  /** Phase represents the memory dump phase */
  phase: string;
  /** Remove represents request of dissociating the memory dump pvc */
  remove?: boolean;
  startTimestamp?: Time;
};
