/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VmObjectMeta } from './vmObjectMeta';
import type { VmVirtualMachineInstanceSpec } from './vmVirtualMachineInstanceSpec';

export type VmVirtualMachineInstanceTemplateSpec = {
  metadata?: VmObjectMeta;
  spec?: VmVirtualMachineInstanceSpec;
};
