/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type VmVolumeSnapshotStatus = {
  /** True if the volume supports snapshotting */
  enabled: boolean;
  /** Volume name */
  name: string;
  /** Empty if snapshotting is enabled, contains reason otherwise */
  reason?: string;
};
