/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmCloudInitConfigDriveSource } from './vmCloudInitConfigDriveSource';
import type { VmCloudInitNoCloudSource } from './vmCloudInitNoCloudSource';
import type { VmConfigMapVolumeSource } from './vmConfigMapVolumeSource';
import type { VmContainerDiskSource } from './vmContainerDiskSource';
import type { VmCoreDataVolumeSource } from './vmCoreDataVolumeSource';
import type { VmDownwardApiVolumeSource } from './vmDownwardApiVolumeSource';
import type { VmDownwardMetricsVolumeSource } from './vmDownwardMetricsVolumeSource';
import type { VmEmptyDiskSource } from './vmEmptyDiskSource';
import type { VmEphemeralVolumeSource } from './vmEphemeralVolumeSource';
import type { VmHostDisk } from './vmHostDisk';
import type { VmMemoryDumpVolumeSource } from './vmMemoryDumpVolumeSource';
import type { VmPersistentVolumeClaimVolumeSource } from './vmPersistentVolumeClaimVolumeSource';
import type { VmSecretVolumeSource } from './vmSecretVolumeSource';
import type { VmServiceAccountVolumeSource } from './vmServiceAccountVolumeSource';
import type { VmSysprepSource } from './vmSysprepSource';

/**
 * Volume represents a named volume in a vmi.
 */
export type VmVolume = {
  cloudInitConfigDrive?: VmCloudInitConfigDriveSource;
  cloudInitNoCloud?: VmCloudInitNoCloudSource;
  configMap?: VmConfigMapVolumeSource;
  containerDisk?: VmContainerDiskSource;
  dataVolume?: VmCoreDataVolumeSource;
  downwardAPI?: VmDownwardApiVolumeSource;
  downwardMetrics?: VmDownwardMetricsVolumeSource;
  emptyDisk?: VmEmptyDiskSource;
  ephemeral?: VmEphemeralVolumeSource;
  hostDisk?: VmHostDisk;
  memoryDump?: VmMemoryDumpVolumeSource;
  /** Volume's name. Must be a DNS_LABEL and unique within the vmi. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names */
  name: string;
  persistentVolumeClaim?: VmPersistentVolumeClaimVolumeSource;
  secret?: VmSecretVolumeSource;
  serviceAccount?: VmServiceAccountVolumeSource;
  sysprep?: VmSysprepSource;
};
