/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VmI6300ESBWatchdog } from './vmI6300ESBWatchdog';

/**
 * Named watchdog device.
 */
export type VmWatchdog = {
  i6300esb?: VmI6300ESBWatchdog;
  /** Name of the watchdog. */
  name: string;
};
