/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { VsphereImage } from './vsphereImage';
import type { VsphereInstanceType } from './vsphereInstanceType';
import type { VsphereNic } from './vsphereNic';
import type { VspherePlacementConfig } from './vspherePlacementConfig';

/**
 * vSphere cloud VM definition spec
 */
export type VsphereMachineSpec = {
  images?: VsphereImage[];
  instanceType?: VsphereInstanceType;
  nics: VsphereNic[];
  /** NTPServers is a list of NTP servers to use instead of the machine image's default NTP server list. */
  ntpServers?: string[];
  placement: VspherePlacementConfig;
  /** VcenterServer is the address of the vSphere endpoint */
  vcenterServer: string;
};
