/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { IPPool } from './iPPool';
import type { ObjectReference } from './objectReference';

export type VsphereNetworkConfig = {
  ipPool?: IPPool;
  /** NetworkName is the name of the network in which VMs are created/located. */
  networkName: string;
  parentPoolRef?: ObjectReference;
  /** support dhcp or static IP, if false, use DHCP */
  staticIp?: boolean;
};
