/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type VsphereCloudAccount = {
  /** Insecure is a flag that controls whether or not to validate the vSphere server's certificate. */
  insecure?: boolean;
  password: string;
  username: string;
  /** VcenterServer is the address of the vSphere endpoint */
  vcenterServer: string;
};
