/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ControlPlaneEndPoint } from './controlPlaneEndPoint';
import type { VspherePlacementConfigEntity } from './vspherePlacementConfigEntity';

export type VsphereClusterConfigEntity = {
  controlPlaneEndpoint?: ControlPlaneEndPoint;
  /** NTPServers is a list of NTP servers to use instead of the machine image's default NTP server list. */
  ntpServers?: string[];
  placement: VspherePlacementConfigEntity;
  /** SSHKeys specifies a list of ssh authorized keys for the 'spectro' user */
  sshKeys?: string[];
  /** whether this cluster should use dhcp or static IP, if false, use DHCP if this is set, then all machinepools should have staticIP with provided IPPool adding this as an additional standalone flag without relating to placement.Nework main reason is to enable more validation for placement.Network.StaticIP which should come together with valid Network.IPPool and Network.Name */
  staticIp?: boolean;
};
