/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */

export type VsphereNetworkConfigEntity = {
  /** NetworkName is the name of the network in which VMs are created/located. */
  networkName: string;
  /** ParentPoolRef Uid to the ParentPool which allocates IPs for this IPPool */
  parentPoolUid?: string;
  /** support dhcp or static IP, if false, use DHCP */
  staticIp?: boolean;
};
