/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { VsphereComputeCluster } from './vsphereComputeCluster';

/**
 * Datacenter and its resources like datastore, resoucepool, folders
 */
export type VsphereComputeClusterResources = {
  computecluster?: VsphereComputeCluster;
  /** Name of the datacenter */
  datacenter?: string;
};
