/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { ClusterWorkloadJob } from './clusterWorkloadJob';
import type { RelatedObject } from './relatedObject';

/**
 * Workspace cluster workload jobs summary
 */
export type WorkspaceClusterWorkloadJobs = {
  jobs?: ClusterWorkloadJob[];
  metadata?: RelatedObject;
};
