/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { WorkspaceClusterWorkloadDeployments } from './workspaceClusterWorkloadDeployments';
import type { ObjectMetaInputEntity } from './objectMetaInputEntity';

/**
 * Workspace clusters workload deployments summary
 */
export type WorkspaceClustersWorkloadDeployments = {
  clusters?: WorkspaceClusterWorkloadDeployments[];
  metadata?: ObjectMetaInputEntity;
};
