/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { WorkspaceClusterRestoreResponse } from './workspaceClusterRestoreResponse';
import type { WorkspaceRestoreState } from './workspaceRestoreState';
import type { Time } from './time';

/**
 * Workspace cluster restore config
 */
export type WorkspaceClusterRestoreConfig = {
  backupName?: string;
  clusterRestoreRefs?: WorkspaceClusterRestoreResponse[];
  restoreState?: WorkspaceRestoreState;
  restoreTime?: Time;
};
