/**
 * Copyright Spectro Cloud 2026
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { WorkspaceClusterRestoreState } from './workspaceClusterRestoreState';

/**
 * Workspace cluster restore response
 */
export type WorkspaceClusterRestoreResponse = {
  backupName?: string;
  clusterName?: string;
  clusterUid?: string;
  restoreStatusMeta?: WorkspaceClusterRestoreState;
  restoreUid?: string;
};
