/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { WorkspaceBackupState } from './workspaceBackupState';
import type { Time } from './time';
import type { WorkspaceClusterBackupResponse } from './workspaceClusterBackupResponse';
import type { WorkspaceBackupStatusConfig } from './workspaceBackupStatusConfig';

/**
 * Workspace cluster backup config
 */
export type WorkspaceClusterBackupConfig = {
  backupName?: string;
  backupState?: WorkspaceBackupState;
  backupTime?: Time;
  clusterBackupRefs?: WorkspaceClusterBackupResponse[];
  config?: WorkspaceBackupStatusConfig;
  requestTime?: Time;
};
