/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { GpuConfig } from './gpuConfig';

/**
 * Workspace resource allocation
 */
export type WorkspaceResourceAllocation = {
  /** @minimum -1 */
  cpuCores?: number;
  gpuConfig?: GpuConfig;
  /** @minimum -1 */
  memoryMiB?: number;
};
