/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.7
 * OpenAPI spec version: v1
 */
import type { ClusterFeatureActor } from './clusterFeatureActor';
import type { WorkspaceClusterRestoreConfig } from './workspaceClusterRestoreConfig';

/**
 * Workspace restore status meta
 */
export type WorkspaceRestoreStatusMeta = {
  actor?: ClusterFeatureActor;
  requestUid?: string;
  workspaceRestoreConfig?: WorkspaceClusterRestoreConfig;
};
