/**
 * Copyright (c) Spectro Cloud
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Palette APIs - 4.8
 * OpenAPI spec version: v1
 */
import type { IncludeClusterResourceMode } from './includeClusterResourceMode';

/**
 * Workspace cluster restore config
 */
export type WorkspaceRestoreConfig = {
  backupName: string;
  includeClusterResourceMode?: IncludeClusterResourceMode;
  /** Deprecated. Use includeClusterResourceMode */
  includeClusterResources?: boolean;
  includeNamespaces?: string[];
  preserveNodePorts?: boolean;
  restorePVs?: boolean;
  sourceClusterUid: string;
};
